package com.mapbox.mapboxsdk.constants;

import java.util.Locale;

public class MapboxConstants {
    public static final int ANIMATION_DURATION = 300;
    public static final long ANIMATION_DURATION_FLING = 500;
    public static final long ANIMATION_DURATION_FLING_BASE = 150;
    public static final int ANIMATION_DURATION_SHORT = 150;
    public static final boolean DEFAULT_SET_STORAGE_EXTERNAL = false;
    public static boolean ENABLE_MAPBOX_LOCATION_SERVICE = true;
    public static final String FRAG_ARG_MAPBOXMAPOPTIONS = "MapboxMapOptions";
    public static final String KEY_META_DATA_SET_STORAGE_EXTERNAL = "com.mapbox.SetStorageExternal";
    public static final Locale MAPBOX_LOCALE = Locale.US;
    public static final double MAXIMUM_DIRECTION = 360.0d;
    public static final float MAXIMUM_SCALE_FACTOR_CLAMP = 1.35f;
    public static final double MAXIMUM_TILT = 60.0d;
    public static final float MAXIMUM_ZOOM = 20.0f;
    public static final double MINIMUM_DIRECTION = 0.0d;
    public static final float MINIMUM_SCALE_FACTOR_CLAMP = 0.65f;
    public static final double MINIMUM_TILT = 0.0d;
    public static final float MINIMUM_ZOOM = 0.0f;
    public static final String STATE_ATTRIBUTION_ENABLED = "mapbox_atrrEnabled";
    public static final String STATE_ATTRIBUTION_GRAVITY = "mapbox_attrGravity";
    public static final String STATE_ATTRIBUTION_MARGIN_BOTTOM = "mapbox_atrrMarginBottom";
    public static final String STATE_ATTRIBUTION_MARGIN_LEFT = "mapbox_attrMarginLeft";
    public static final String STATE_ATTRIBUTION_MARGIN_RIGHT = "mapbox_attrMarginRight";
    public static final String STATE_ATTRIBUTION_MARGIN_TOP = "mapbox_attrMarginTop";
    public static final String STATE_CAMERA_POSITION = "mapbox_cameraPosition";
    public static final String STATE_COMPASS_ENABLED = "mapbox_compassEnabled";
    public static final String STATE_COMPASS_FADE_WHEN_FACING_NORTH = "mapbox_compassFade";
    public static final String STATE_COMPASS_GRAVITY = "mapbox_compassGravity";
    public static final String STATE_COMPASS_IMAGE_BITMAP = "mapbox_compassImage";
    public static final String STATE_COMPASS_MARGIN_BOTTOM = "mapbox_compassMarginBottom";
    public static final String STATE_COMPASS_MARGIN_LEFT = "mapbox_compassMarginLeft";
    public static final String STATE_COMPASS_MARGIN_RIGHT = "mapbox_compassMarginRight";
    public static final String STATE_COMPASS_MARGIN_TOP = "mapbox_compassMarginTop";
    public static final String STATE_DEBUG_ACTIVE = "mapbox_debugActive";
    public static final String STATE_DOUBLE_TAP_ENABLED = "mapbox_doubleTapEnabled";
    public static final String STATE_DOUBLE_TAP_ENABLED_CHANGE = "mapbox_doubleTapEnabledChange";
    public static final String STATE_HAS_SAVED_STATE = "mapbox_savedState";
    public static final String STATE_LOCATION_CHANGE_ANIMATION_ENABLED = "mapbox_locationChangeAnimationEnabled";
    public static final String STATE_LOGO_ENABLED = "mapbox_logoEnabled";
    public static final String STATE_LOGO_GRAVITY = "mapbox_logoGravity";
    public static final String STATE_LOGO_MARGIN_BOTTOM = "mapbox_logoMarginBottom";
    public static final String STATE_LOGO_MARGIN_LEFT = "mapbox_logoMarginLeft";
    public static final String STATE_LOGO_MARGIN_RIGHT = "mapbox_logoMarginRight";
    public static final String STATE_LOGO_MARGIN_TOP = "mapbox_logoMarginTop";
    public static final String STATE_MY_BEARING_TRACKING_DISMISS = "mapbox_myBearingTrackingDismiss";
    public static final String STATE_MY_BEARING_TRACKING_MODE = "mapbox_myBearingTracking";
    public static final String STATE_MY_LOCATION_ENABLED = "mapbox_myLocationEnabled";
    public static final String STATE_MY_LOCATION_TRACKING_DISMISS = "mapbox_myLocationTrackingDismiss";
    public static final String STATE_MY_LOCATION_TRACKING_MODE = "mapbox_myLocationTracking";
    public static final String STATE_ROTATE_ENABLED = "mapbox_rotateEnabled";
    public static final String STATE_ROTATE_ENABLED_CHANGE = "mapbox_rotateEnabledChange";
    public static final String STATE_SCROLL_ENABLED = "mapbox_scrollEnabled";
    public static final String STATE_SCROLL_ENABLED_CHANGE = "mapbox_scrollEnabledChange";
    public static final String STATE_STYLE_URL = "mapbox_styleUrl";
    public static final String STATE_TILT_ENABLED = "mapbox_tiltEnabled";
    public static final String STATE_TILT_ENABLED_CHANGE = "mapbox_tiltEnabledChange";
    public static final String STATE_USING_CUSTOM_LOCATION_SOURCE = "mapbox_usingCustomLocationSource";
    public static final String STATE_ZOOM_CONTROLS_ENABLED = "mapbox_zoomControlsEnabled";
    public static final String STATE_ZOOM_ENABLED = "mapbox_zoomEnabled";
    public static final String STATE_ZOOM_ENABLED_CHANGE = "mapbox_zoomEnabledChange";
    public static final float UNMEASURED = -1.0f;
    public static final long VELOCITY_THRESHOLD_IGNORE_FLING = 300;
}
