package defpackage;

/* renamed from: aaep */
public enum aaep {
    LEAVE_APP,
    BLACKLISTED_CANNOT_PLAY,
    THIRD_PARTY_ONBOARD,
    FIRST_TIME_OPEN_DRAWER,
    LAUNCH_END_CALL,
    PLAY_WITH_INVALID_SELECTION,
    PLAY_WITH_FAIL_CREATE_GROUP,
    INVITE_EXCEED_MAXIMUM,
    WEBGL_DISABLED_CANNOT_PLAY
}
