package defpackage;

/* renamed from: aage */
public enum aage {
    CAMERA_LENS_CAROUSEL,
    CAMERA_ROLL,
    CAMERA_SNAP_CODE,
    CHAT_DEEEPLINK,
    CHAT_DIRECT,
    CHAT_DIRECT_DISCOVER_DEEPLINK,
    CHAT_DIRECT_PDP,
    CHAT_DIRECT_SCAN_CODE_DEEPLINK,
    CHAT_DIRECT_TOP_SNAP,
    CHAT_SNAP,
    DISCOVER_FEED,
    EXTERNAL_DEEPLINK,
    EXTERNAL_SCAN_CODE_DEEPLINK,
    INTERNAL_WEB_VIEW,
    ODG,
    MAP,
    MINI_PROFILE_STORY,
    PAYMENT_SETTINGS,
    PREVIEW,
    SCAN_HISTORY,
    SEARCH,
    SNAP_AD,
    SPECTACLES_SETTING_CELL,
    STORY_FEED,
    STORY_FRIEND_FEED,
    SNAP_STORE_CELL_SETTINGS,
    SNAP_STORE_CELL_SETTINGS_V2,
    USER_PROFILE,
    UNKNOWN
}
