package defpackage;

/* renamed from: aalv */
public enum aalv {
    VISUAL_MISS_ETIKATE,
    VISUAL_INSTASNAP,
    VISUAL_GRAYSCALE,
    VISUAL_SMOOTHING,
    VISUAL_CONTEXT_SKY,
    VISUAL_CONTEXT_PORTRAIT,
    INFO_TIMESTAMP,
    INFO_WEATHER,
    INFO_SPEED,
    INFO_BATTERY,
    INFO_ALTITUDE,
    MOTION_SLOW,
    MOTION_FAST,
    MOTION_SUPER_FAST,
    MOTION_REVERSE,
    STREAK
}
