package defpackage;

/* renamed from: aamp */
public enum aamp {
    THUMBNAIL,
    FULLSCREEN_SWIPE,
    FULLSCREEN_TAP_AND_HOLD,
    CHAT_DRAWER,
    FULLSCREEN_BUTTON_PRESS,
    FULLSCREEN_LONG_PRESS,
    GRID_ACTION_MENU_TAP,
    GRID_ACTION_MENU_PAN,
    GRID_SELECT_MODE,
    GALLERY_EDIT,
    MEMORIES_POCKET,
    RECENTLY_TAKEN,
    ADD_TO_STORY_BUTTON_TAP
}
