package defpackage;

/* renamed from: aaty */
public enum aaty {
    DEFAULT,
    PROFILE_STORY,
    PROFILE_UP_NEXT,
    PROFILE_SHOW_SEASON,
    PROFILE_MOMENTS,
    PROFILE_PUBLISHER_EDITIONS,
    PROFILE_PUBLISHER_LATEST_EDITION,
    PROFILE_SUGGESTIONS,
    PROFILE_POPULAR_LENSES,
    PROFILE_RECENT_LENSES
}
