package defpackage;

/* renamed from: aayj */
public enum aayj {
    EMOJI_SUGGESTION,
    PRE_TYPE,
    PRE_TYPE_QUERY_SUGGESTION,
    POST_TYPE_QUERY_SUGGESTION,
    POST_TYPE_QUERY_SPELL_CORRECTED_SUGGESTION,
    POST_TYPE_QUERY_SPELL_ESCAPE_HATCH_SUGGESTION,
    QUERY_SUGGESTION,
    RELATED_SEARCH,
    SECTION_HEADER_REFRESH_BUTTON,
    SECTION_HEADER_MANUAL_RELOAD_BUTTON,
    SEARCH_BAR,
    SEARCH_BAR_RETURN,
    SNAP_TAB,
    VIEW_MORE
}
