package defpackage;

/* renamed from: abfy */
public enum abfy {
    USER_PUBLIC,
    USER_PRIVATE,
    OFFICIAL,
    MY,
    LOCAL,
    LIVE,
    AD,
    LAGUNA_DAY_ALL,
    LAGUNA_DAY_HIGHLIGHT,
    LAGUNA,
    DYNAMIC,
    DYNAMIC_NYC,
    GROUP_CUSTOM,
    GROUP_GEO_FRIENDS,
    GROUP_GEO_FRIENDS_OF_FRIENDS,
    GROUP_PRIVATE,
    GROUP_MISCHIEF,
    PUBLIC_ONLY_FRIENDS,
    LIVE_CURATED,
    GENERATED,
    PUBLISHER,
    SHOW,
    IMPALA,
    THIRD_PARTY_APP
}
