package defpackage;

import com.google.common.base.MoreObjects;
import com.google.gson.annotations.SerializedName;
import com.snap.core.db.record.GeofilterModel;
import com.snap.core.db.record.StickerMessageModel;
import com.snap.core.db.record.UnlockablesModel;

/* renamed from: acam */
public final class acam {
    @SerializedName(alternate = {"a"}, value = "type")
    public final int a;
    @SerializedName(alternate = {"b"}, value = "isRecent")
    final boolean b;
    @SerializedName(alternate = {"c"}, value = "isFromSearch")
    final boolean c;
    @SerializedName("isAutoGenerated")
    final boolean d = false;
    @SerializedName(alternate = {"d"}, value = "isGeoSticker")
    final boolean e;
    @SerializedName(alternate = {"e"}, value = "emojiCode")
    public final String f;
    @SerializedName(alternate = {"f"}, value = "packId")
    public final String g;
    @SerializedName(alternate = {"g"}, value = "stickerId")
    public final String h;
    @SerializedName(alternate = {"h"}, value = "position")
    public final acas i;
    @SerializedName(alternate = {"i"}, value = "rotationInClockwiseDegrees")
    public final double j;
    @SerializedName(alternate = {"j"}, value = "scale")
    public final double k;
    @SerializedName(alternate = {"m"}, value = "relativeWidth")
    public final double l;
    @SerializedName(alternate = {"n"}, value = "relativeHeight")
    public final double m;
    @SerializedName(alternate = {"o"}, value = "isPinned")
    public final boolean n;
    @SerializedName(alternate = {"p"}, value = "normalizedTrajectory")
    public final acar<acaq> o;
    @SerializedName("infoStickerType")
    public final String p;
    @SerializedName("infoStickerStyle")
    public final agpd q;
    @SerializedName("isUnlockableSticker")
    final boolean r;
    @SerializedName("isAnimated")
    public final boolean s;
    @SerializedName("externalSrcUrl")
    public final String t;
    @SerializedName("unlockableId")
    final String u;
    @SerializedName(alternate = {"k"}, value = "width")
    private final double v;
    @SerializedName(alternate = {"l"}, value = "height")
    private final double w;

    /* renamed from: acam$a */
    public static class a {
        public int a;
        boolean b;
        boolean c;
        boolean d;
        public String e;
        String f;
        String g;
        public String h;
        double i;
        double j;
        double k;
        double l;
        public double m;
        public double n;
        public acas o;
        double p;
        double q;
        public double r;
        public double s;
        public boolean t;
        public acar<acaq> u;
        public String v;
        public agpd w;
        public boolean x;

        public final a a(double d) {
            this.i = d;
            return this;
        }

        public final a a(int i) {
            this.a = i;
            return this;
        }

        public final a a(acar<acaq> acar) {
            this.u = acar;
            return this;
        }

        public final a a(acas acas) {
            this.o = acas;
            return this;
        }

        public final a a(agpd agpd) {
            this.w = agpd;
            return this;
        }

        public final a a(String str) {
            this.e = str;
            return this;
        }

        public final a a(String str, String str2) {
            this.f = str;
            this.g = str2;
            return this;
        }

        public final a a(boolean z) {
            this.b = z;
            return this;
        }

        public final acam a() {
            return new acam(this);
        }

        public final a b(double d) {
            this.j = d;
            return this;
        }

        public final a b(String str) {
            this.h = str;
            return this;
        }

        public final a b(boolean z) {
            this.c = z;
            return this;
        }

        public final a c(double d) {
            this.m = d;
            return this;
        }

        public final a c(String str) {
            this.v = str;
            return this;
        }

        public final a c(boolean z) {
            this.d = z;
            return this;
        }

        public final a d(double d) {
            this.n = d;
            return this;
        }

        public final a d(boolean z) {
            this.t = z;
            return this;
        }

        public final a e(double d) {
            this.l = d;
            return this;
        }

        public final a e(boolean z) {
            this.x = z;
            return this;
        }

        public final a f(double d) {
            this.k = d;
            return this;
        }

        public final a g(double d) {
            this.q = d;
            return this;
        }

        public final a h(double d) {
            this.p = d;
            return this;
        }

        public final a i(double d) {
            this.r = d;
            return this;
        }

        public final a j(double d) {
            this.s = d;
            return this;
        }
    }

    public acam(a aVar) {
        this.a = aVar.a;
        this.b = aVar.b;
        this.c = aVar.c;
        this.e = aVar.d;
        this.r = false;
        this.s = aVar.x;
        this.f = aVar.e;
        this.g = aVar.f;
        this.h = aVar.g;
        this.t = aVar.h;
        if (aVar.o == null) {
            if (aVar.k == 0.0d || aVar.l == 0.0d) {
                throw new IllegalStateException("Cant create normalized point if width and height are not set");
            }
            float max = (float) Math.max(aVar.l, aVar.k);
            float min = (float) Math.min(aVar.l, aVar.k);
            double d = aVar.i;
            double d2 = (double) min;
            Double.isNaN(d2);
            d /= d2;
            d2 = aVar.j;
            double d3 = (double) max;
            Double.isNaN(d3);
            aVar.o = new acas(d, d2 / d3);
        }
        this.i = aVar.o;
        this.j = aVar.m;
        this.k = aVar.n;
        this.v = aVar.q;
        this.w = aVar.p;
        this.l = aVar.r;
        this.m = aVar.s;
        this.n = aVar.t;
        this.o = aVar.u;
        this.p = aVar.v;
        this.q = aVar.w;
        this.u = null;
    }

    public final int a() {
        return this.a;
    }

    public final boolean b() {
        return this.b;
    }

    public final boolean c() {
        return this.c;
    }

    public final boolean d() {
        return this.e;
    }

    public final String e() {
        return this.f;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        acam acam = (acam) obj;
        boolean z = this.n;
        if (z != acam.n) {
            return false;
        }
        akmc akmc;
        Object obj2;
        if (z) {
            akmc = new akmc();
            obj2 = this.o;
            obj = acam.o;
        } else {
            akmc = new akmc().a(this.a, acam.a).a(this.b, acam.b).a(this.c, acam.c).a(this.d, acam.d).a(this.e, acam.e).a(this.f, acam.f).a(this.i, acam.i).a(this.j, acam.j).a(this.k, acam.k).a(this.p, acam.p).a(this.q, acam.q).a(this.r, acam.r).a(this.s, acam.s).a(this.t, acam.t);
            obj2 = this.u;
            obj = acam.u;
        }
        return akmc.a(obj2, obj).a;
    }

    public final String f() {
        return this.g;
    }

    public final String g() {
        return this.h;
    }

    public final acas h() {
        return this.i;
    }

    public final int hashCode() {
        return new akmd().a(this.a).a(this.b).a(this.c).a(this.d).a(this.e).a(this.f).a(this.g).a(this.h).a(this.i).a(this.j).a(this.k).a(this.v).a(this.w).a(this.l).a(this.m).a(this.n).a(this.o).a(this.p).a(this.q).a(this.r).a(this.s).a(this.t).a(this.u).a;
    }

    public final double i() {
        return this.j;
    }

    public final double j() {
        return this.k;
    }

    public final double k() {
        return this.v;
    }

    public final double l() {
        return this.w;
    }

    public final double m() {
        return this.l;
    }

    public final double n() {
        return this.m;
    }

    public final boolean o() {
        return this.n;
    }

    public final String p() {
        return this.u;
    }

    public final acar<acaq> q() {
        return this.o;
    }

    public final acar<acaq> r() {
        acar acar = this.o;
        if (acar != null && !acar.a.isEmpty()) {
            return this.o;
        }
        acar = new acar();
        acar.a(0, new acaq((float) Math.toRadians(this.j), (float) this.k, (float) abpp.a(Double.valueOf(this.i.a)), (float) abpp.a(Double.valueOf(this.i.b))));
        return acar;
    }

    public final String s() {
        return this.p;
    }

    public final agpd t() {
        return this.q;
    }

    public final String toString() {
        String str = "isRecent";
        str = "isFromSearch";
        str = "isAutoGenerated";
        str = "isGeoSticker";
        str = "emojiCode";
        str = "position";
        String str2 = "rotationInClockwiseDegrees";
        str2 = "scale";
        str2 = "width";
        str2 = "height";
        str2 = "relativeWidth";
        str2 = "relativeHeight";
        str = "isPinned";
        str = "timeTransforms";
        str = "infoStickerType";
        str = "infoStickerStyle";
        str = "isUnlockableSticker";
        str = "externalSrcUrl";
        return MoreObjects.toStringHelper((Object) this).add("type", this.a).add(str, this.b).add(str, this.c).add(str, this.d).add(str, this.e).add(str, this.f).add(StickerMessageModel.PACKID, this.g).add(StickerMessageModel.STICKERID, this.h).add(str, this.i).add(str2, this.j).add(str2, this.k).add(str2, this.v).add(str2, this.w).add(str2, this.l).add(str2, this.m).add(str, this.n).add(str, this.o).add(str, this.p).add(str, this.q).add(str, this.r).add(GeofilterModel.ISANIMATED, this.s).add(str, this.t).add(UnlockablesModel.UNLOCKABLEID, this.u).toString();
    }

    public final boolean u() {
        return this.r;
    }

    public final boolean v() {
        return this.s;
    }

    public final String w() {
        return this.t;
    }
}
