package defpackage;

/* renamed from: adlh */
public enum adlh {
    PLAYER_BEGIN_SETUP,
    GL_CONTEXT_FINISH_SETUP,
    VIDEO_COMPONENT_BEGIN_SETUP,
    VIDEO_COMPONENT_FINISH_SETUP,
    AUDIO_COMPONENT_BEGIN_SETUP,
    AUDIO_COMPONENT_FINISH_SETUP,
    PLAYER_FINISH_SETUP,
    PLAYER_START,
    PLAYER_FIRST_FRAME,
    PLAYER_BEGIN_RESTART,
    PLAYER_FINISH_RESTART,
    PLAYER_EXIT
}
