package defpackage;

import android.support.v7.widget.helper.ItemTouchHelper.Callback;
import com.brightcove.player.mediacontroller.BrightcoveMediaController;
import com.google.gson.reflect.TypeToken;
import com.mapbox.mapboxsdk.constants.MapboxConstants;
import com.snap.ui.view.TakeSnapButton;
import com.snap.ui.view.multisnap.MultiSnapThumbnailTilesViewControllerKt;
import defpackage.fth.a;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

/* renamed from: dnd */
public enum dnd implements fth {
    CAMERA_TYPE(a.a(ebx.FRONT_FACING)),
    CAMERA_USAGE_TYPE(a.a(edi.MAIN)),
    CAMERA2_LEVEL(a.a(ebz.UNKNOWN)),
    SCAN_ENABLED(a.a(true)),
    USE_CAMERA2(a.a(false)),
    ASYNC_RELEASE_CAMERA(a.a(false)),
    TAKE_PICTURE_METHOD(a.a(2)),
    CAMERA1_FRONT_FACING_TAKE_PICTURE_API_WITH_FLASH(a.a(false)),
    CAMERA1_BACK_FACING_TAKE_PICTURE_API_WITH_FLASH(a.a(false)),
    CAMERA1_MAIN_CAMERA_FRONT_FACING_TAKE_PICTURE_API(a.a(false)),
    CAMERA1_MAIN_CAMERA_BACK_FACING_TAKE_PICTURE_API(a.a(false)),
    CAMERA1_FEED_CAMERA_FRONT_FACING_TAKE_PICTURE_API(a.a(false)),
    CAMERA1_FEED_CAMERA_BACK_FACING_TAKE_PICTURE_API(a.a(false)),
    CAMERA2_FRONT_FACING_TAKE_PICTURE_API_WITH_FLASH(a.a(false)),
    CAMERA2_BACK_FACING_TAKE_PICTURE_API_WITH_FLASH(a.a(false)),
    CAMERA2_FRONT_FACING_TAKE_PICTURE_API_STATE(a.a(false)),
    CAMERA2_BACK_FACING_TAKE_PICTURE_API_STATE(a.a(true)),
    CAMERA1_FRONT_FACING_TAKE_PICTURE_API_TIMEOUT_MS(a.a(5000)),
    CAMERA1_BACK_FACING_TAKE_PICTURE_API_TIMEOUT_MS(a.a(5000)),
    CAMERA1_TAKE_PICTURE_NO_CALLBACK_WAITING_MS(a.a(5000)),
    CAMERA1_TAKE_PICTURE_API_FRONT_FACING_NEW_TIMEOUT_CONTROL_STATE(a.a(false)),
    CAMERA1_TAKE_PICTURE_API_BACK_FACING_NEW_TIMEOUT_CONTROL_STATE(a.a(false)),
    CAMERA1_TAKE_PICTURE_API_FRONT_FACING_NEW_TIMEOUT_CONTROL_TIMEOUT_MS(a.a(5000)),
    CAMERA1_TAKE_PICTURE_API_BACK_FACING_NEW_TIMEOUT_CONTROL_TIMEOUT_MS(a.a(5000)),
    CAMERA1_FRONT_FACING_SHOULD_DISABLE_SHUTTER_SOUND(a.a(true)),
    CAMERA1_BACK_FACING_SHOULD_DISABLE_SHUTTER_SOUND(a.a(true)),
    CAMERA1_FRONT_FACING_SHOULD_DISABLE_SHUTTER_SOUND_BY_NULL_SHUTTER_CALLBACK(a.a(false)),
    CAMERA1_BACK_FACING_SHOULD_DISABLE_SHUTTER_SOUND_BY_NULL_SHUTTER_CALLBACK(a.a(false)),
    CAMERA1_FRONT_FACING_MOCK_SHUTTER_CALLBACK_TIME_MS(a.a(200)),
    CAMERA1_BACK_FACING_MOCK_SHUTTER_CALLBACK_TIME_MS(a.a(200)),
    CAMERA1_FRONT_FACING_SHARPNESS_ADJUSTMENT_ENABLED(a.a(false)),
    CAMERA1_FRONT_FACING_SHARPNESS_PERCENTAGE(a.a(-1.0f)),
    ENABLE_MULTI_SNAP(a.a(true)),
    RECORD_THREE_SECOND_SEGMENT(a.a(false)),
    SUGGESTED_BITRATE(a.a(16000000)),
    IS_CAMERA1_ZSL_ENABLED(a.a(false)),
    IS_CAMERA2_ZSL_ENABLED_FRONT_FACING(a.a(false)),
    IS_CAMERA2_ZSL_ENABLED_BACK_FACING(a.a(false)),
    CAMERA2_LOWLIGHT_COMPENSATION_VALUE(a.a(1.0f)),
    CAMERA2_STILL_CAPTURE_INTENT_ENABLED(a.a(true)),
    PICTURE_NOISE_REDUCTION_MODE_OVERRIDE(a.a(-1)),
    NATIVE_FRONT_FACING_ZOOM_ENABLED(a.a(true)),
    VIDEO_STABILIZATION_ENABLED(a.a(true)),
    AUTO_FOCUS_WITH_TORCH_ENABLED(a.a(true)),
    MULTIPLE_FRAME_BUFFER_ENABLED(a.a(false)),
    USE_IMAGE_READER_FOR_SCREENSHOT(a.a(false)),
    VIDEO_HIGH_QUALITY_RECORDING(a.a(false)),
    VIDEO_HIGH_BITRATE_RECORDING(a.a(false)),
    DISABLE_DISTORTION_CORRECTION(a.a(false)),
    CAN_SET_JPEG_THUMBNAIL_SIZE_TO_ZERO(a.a(false)),
    MODIFIED_MAX_ZOOM_ENABLED(a.a(false)),
    BACK_FACING_FLASH_PHOTO_CAPTURE_DELAY(a.a(0)),
    LIGHT_MODE_CONTROLLER_WINDOW_SIZE(a.a(5)),
    CAMERA1_FRONT_FACING_RECORDING_HINT_TIMING(a.a(2)),
    CAMERA1_BACK_FACING_RECORDING_HINT_TIMING(a.a(2)),
    AUTOFOCUS_TIMEOUT(a.a((int) BrightcoveMediaController.DEFAULT_TIMEOUT)),
    PREPARE_RECORDING_DELAY(a.a((int) MapboxConstants.ANIMATION_DURATION)),
    START_RECORDING_DELAY(a.a(400)),
    SC_MEDIA_RECORDER_RECOMMENDED(a.a(true)),
    SC_MEDIA_RECORDER_ENABLED(a.a(true)),
    ANDROID_MEDIA_RECORDER_SURFACE_RECORDING_ENABLED(a.a(true)),
    HIGH_CONSTANT_FPS_SCHEME_ENABLED(a.a(false)),
    BUFFER_COUNT_FOR_MULTIPLE_FRAME_BUFFER(a.a(3)),
    PREVIEW_RESOLUTION_PROVIDER(a.a(1)),
    RECORDING_RESOLUTION_PROVIDER(a.a(1)),
    PICTURE_RESOLUTION_PROVIDER(a.a(1)),
    PREVIEW_RESOLUTION_UPPER_BOUND(a.a(1080)),
    CAMERA2_PICTURE_MODE(a.a(ecf.JPEG)),
    NO_TRANSCODING_TARGET_HEIGHT(a.a(400)),
    CAMERA2_LOWLIGHT_ISO_THRESHOLD(a.a(800)),
    VIDEO_RECORDING_PLAYBACK_ORIENTATION_HINT(a.a(90)),
    VIDEO_TRANSCODING_PLAYBACK_ORIENTATION_HINT(a.a(90)),
    MP4METADATA_VIDEO_CHECK_ENABLED(a.a(false)),
    CAMERA2_ISO_BUG_DETECTION(a.a(false)),
    CAMERA2_LOWLIGHT_MODE_ENABLED(a.a(false)),
    FORCE_CAMERA_30_FPS(a.a(false)),
    SAMSUNG_AAC_CODEC_ENABLED(a.a(false)),
    MEDIA_QUALITY_AUTOMATION_TEST_ENABLED(a.a(false)),
    MEDIA_RECORDER_USE_SINGLETON_THREAD(a.a(false)),
    AUDIO_BUFFER_ENABLED(a.a(false)),
    RECORDER_GOP_SIZE(a.a(30)),
    SHOULD_RECORDER_REQUEST_IFRAME_MANUALLY(a.a(true)),
    ENABLE_SAMSUNG_CAMERA_SDK_FRONT_FACING(a.a(false)),
    ENABLE_SAMSUNG_CAMERA_SDK_BACK_FACING(a.a(false)),
    BATCH_CAPTURE(a.a(false)),
    BATCH_CAPTURE_MAX_NUMBER_OF_SNAPS(a.a(10)),
    RESET_AFTER_CAPTURE(a.a(false)),
    ENABLE_COUNT_DOWN_TIMER(a.a(false)),
    ENABLE_PORTRAIT_MODE(a.a(false)),
    PORTRAIT_MODE_TEXTURE_RENDERER_BLUR_RADIUS(a.a(2)),
    PORTRAIT_MODE_SCALE_RATIO_BEFORE_UPDATE(a.a(0.1f)),
    PORTRAIT_MODE_GUIDED_FILTER_ENABLED(a.a(true)),
    ENABLE_CONSTANT_QUALITY_MODE_RECORDING(a.a(false)),
    CAMERA2_SUGGESTED_HARDWARE_LEVEL(a.a(ebz.LIMITED.ordinal())),
    ENABLE_GRID_LEVEL(a.a(false)),
    DEVICE_GRAVITY_SENSOR_ADAPTER_LPF_FLOAT_ALPHA(a.a(0.9f)),
    FORCE_SCREENSHOT_BY_SNAP_CAPTURE_SOURCE_SET(a.a(new 1().getType(), r10)),
    FRONT_FACING_FORCE_SCREENSHOT_BY_SNAP_CAPTURE_SOURCE_SET(a.a(new 2().getType(), r10)),
    TAKE_PICTURE_STARTUP_COOLDOWN_ENABLED(a.a(false)),
    TAKE_PICTURE_COLDSTART_COOLDOWN_DURATION_SECONDS(a.a(0)),
    TAKE_PICTURE_WARMSTART_COOLDOWN_DURATION_SECONDS(a.a(0)),
    ENABLE_FACE_PRIORITY(a.a(false)),
    ENABLE_TAP_TO_EXPOSURE(a.a(false)),
    GLES3_ALLOWED(a.a(false)),
    OFF_SCREEN_SCREENSHOT_ENABLED(a.a(false)),
    TAKE_PICTURE_API_RESOLUTION_LOWER_BOUND(a.a(0)),
    CAMERA1_FRONT_FACING_PICTURE_TARGET_HEIGHT(a.a(720)),
    CAMERA1_BACK_FACING_PICTURE_TARGET_HEIGHT(a.a(720)),
    CAMERA2_GPU_PHOTO_TARGET_HEIGHT(a.a(1152)),
    CAMERA2_JPEG_PICTURE_TARGET_HEIGHT(a.a(1152)),
    FRONT_FACING_PREVIEW_RESOLUTION_OVERRIDE(a.a((Type) abtl.class, r9)),
    BACK_FACING_PREVIEW_RESOLUTION_OVERRIDE(a.a((Type) abtl.class, r9)),
    FRONT_FACING_RECORDING_RESOLUTION_OVERRIDE(a.a((Type) abtl.class, r9)),
    BACK_FACING_RECORDING_RESOLUTION_OVERRIDE(a.a((Type) abtl.class, r9)),
    FRONT_FACING_PICTURE_RESOLUTION_OVERRIDE(a.a((Type) abtl.class, r9)),
    BACK_FACING_PICTURE_RESOLUTION_OVERRIDE(a.a((Type) abtl.class, r9)),
    USE_TRANSCODING(a.a(true)),
    ENABLE_FACE_ACCESSIBILITY(a.a(false)),
    FACE_ACCESSIBILITY_EDGE_PIXEL(a.a((int) Callback.DEFAULT_DRAG_ANIMATION_DURATION)),
    FACE_ACCESSIBILITY_INTERVAL_MS(a.a((int) Callback.DEFAULT_DRAG_ANIMATION_DURATION)),
    FACE_ACCESSIBILITY_ANNOUNCEMENT_DELAY_MS(a.a((int) TakeSnapButton.LONG_PRESS_TIME)),
    ENABLE_CAMERA2_OIS(a.a(false)),
    MULTISNAP_MIN_LAST_SEGMENT_LENGTH(a.a((int) TimeUnit.SECONDS.toMillis(1))),
    ENABLE_SHUTTER_PRIORITY(a.a(false)),
    SHUTTER_PRIORITY_ISO_MAX_THRESHOLD(a.a((int) MultiSnapThumbnailTilesViewControllerKt.THUMBNAIL_SELECTED_INTERVAL)),
    SHUTTER_PRIORITY_EXPOSURE_MAX_THRESHOLD_NS(a.a(100000000)),
    CAMERA_ROTATION_CONSTANT(a.a(0)),
    IMAGE_READER_OR_PB_SURFACE_READER_SUPPORT(a.a(false)),
    FRONT_SENSOR_SIZE(a.a((Type) abpr.class, r9)),
    BACK_SENSOR_SIZE(a.a((Type) abpr.class, r9)),
    BUGGY_PREVIEW_SIZES(a.a(new 3().getType(), r10)),
    SHOULD_SET_NULL_ISO_CAMERA2(a.a(false)),
    FORCE_FACE_STATISTICS_FOR_FACE_PRIORITY(a.a(false)),
    IS_CODEC_LEASING_ENGINE_ENABLED_IN_MUSHROOM(a.a(false)),
    CODEC_LEASE_TIMEOUT_THRESHOLD(a.a(120000)),
    ENABLE_SOFTWARE_ENCODER(a.a(false)),
    HAS_SEEN_TAKE_SNAP_ONBOARDING_MESSAGE(a.a(false)),
    HANDS_FREE_ENABLED_COUNT(a.a(0)),
    HANDS_FREE_SEEN_COUNT(a.a(0)),
    VIDEOCHAT_HW_AVC(a.a(3)),
    VIDEOCHAT_HW_HEVC(a.a(0)),
    VIDEOCHAT_HW_VP8(a.a(3)),
    ENABLE_MEDIA_RECOVERY(a.a(false)),
    ENABLE_BATCH_CAPTURE_RECOVERY(a.a(false)),
    MEDIA_RECOVERY_TIMEOUT(a.a(TimeUnit.HOURS.toMillis(1))),
    MEDIA_RECOVERY_CRASH_MAXIMUM(a.a(3)),
    MEDIA_RECOVERY_CRASH_COUNT(a.a(0)),
    ENABLE_UNIFIED_CAMERA_OPEN(a.a(false)),
    EARLY_INIT_RECORDER_ENABLED(a.a(false)),
    DELAY_RELEASE_RECORDER_MS(a.a(5000)),
    FORCE_TO_USE_SOFTWARE_RECORDING(a.a(false)),
    SHOULD_REPORT_FRONT_CAMERA1_CAPACITY_FOR_MUSHROOM(a.a(true)),
    SHOULD_REPORT_BACK_CAMERA1_CAPACITY_FOR_MUSHROOM(a.a(true)),
    SHOULD_REPORT_CAMERA2_CAPACITY_FOR_MUSHROOM(a.a(true)),
    MICROPHONE_PERMISSION_RESULT_STATE(a.a(ifv.UNKNOWN)),
    START_IMAGE_PREVIEW_ON_TOUCH_UP(a.a(false)),
    PREPARE_EGL_BEFORE_CREATING_TEXTURE(a.a(false)),
    OPEN_CAMERA_ON_CAMERA_PAGE_ONLY(a.a(false)),
    FRIENDS_SWIPE_TEACHING_TOOLTIP_ENABLED(a.a(false)),
    SEEN_FRIENDS_PAGE_ONBOARDING_TOOLTIP(a.a(false));
    
    private final a<?> delegate;

    /* renamed from: dnd$1 */
    static class 1 extends TypeToken<Set<String>> {
        1() {
        }
    }

    /* renamed from: dnd$2 */
    static class 2 extends TypeToken<Set<String>> {
        2() {
        }
    }

    /* renamed from: dnd$3 */
    static class 3 extends TypeToken<List<abtl>> {
        3() {
        }
    }

    private dnd(a<?> aVar) {
        this.delegate = aVar;
    }

    public final a<?> a() {
        return this.delegate;
    }

    public final ftg b() {
        return ftg.CAMERA;
    }
}
