package defpackage;

/* renamed from: gcq */
public final /* synthetic */ class gcq {
    public static final /* synthetic */ int[] a;
    public static final /* synthetic */ int[] b;
    public static final /* synthetic */ int[] c;
    public static final /* synthetic */ int[] d;
    public static final /* synthetic */ int[] e;
    public static final /* synthetic */ int[] f;
    public static final /* synthetic */ int[] g;
    public static final /* synthetic */ int[] h;
    public static final /* synthetic */ int[] i;

    static {
        int[] iArr = new int[gcp.values().length];
        a = iArr;
        iArr[gcp.VIDEO.ordinal()] = 1;
        a[gcp.VIDEO_NO_SOUND.ordinal()] = 2;
        a[gcp.LAGUNA_SOUND.ordinal()] = 3;
        a[gcp.MALIBU_SOUND.ordinal()] = 4;
        a[gcp.LAGUNAHD_SOUND.ordinal()] = 5;
        a[gcp.NEWPORT_SOUND.ordinal()] = 6;
        a[gcp.LAGUNA_NO_SOUND.ordinal()] = 7;
        a[gcp.MALIBU_NO_SOUND.ordinal()] = 8;
        a[gcp.LAGUNAHD_NO_SOUND.ordinal()] = 9;
        a[gcp.NEWPORT_NO_SOUND.ordinal()] = 10;
        a[gcp.AUDIO_STITCH.ordinal()] = 11;
        a[gcp.AUDIO.ordinal()] = 12;
        a[gcp.IMAGE.ordinal()] = 13;
        a[gcp.FRIEND_DEPRECATED.ordinal()] = 14;
        a[gcp.BLOB.ordinal()] = 15;
        a[gcp.GIF.ordinal()] = 16;
        a[gcp.FINGERPRINT_HEADER_SIZE.ordinal()] = 17;
        a[gcp.PSYCHOMANTIS.ordinal()] = 18;
        a[gcp.SCREAMINGMANTIS.ordinal()] = 19;
        a[gcp.GHOSTMANTIS.ordinal()] = 20;
        a[gcp.UNKNOWN.ordinal()] = 21;
        iArr = new int[gcp.values().length];
        b = iArr;
        iArr[gcp.GIF.ordinal()] = 1;
        iArr = new int[gcp.values().length];
        c = iArr;
        iArr[gcp.IMAGE.ordinal()] = 1;
        c[gcp.PSYCHOMANTIS.ordinal()] = 2;
        c[gcp.SCREAMINGMANTIS.ordinal()] = 3;
        c[gcp.GHOSTMANTIS.ordinal()] = 4;
        c[gcp.AUDIO.ordinal()] = 5;
        c[gcp.VIDEO.ordinal()] = 6;
        c[gcp.VIDEO_NO_SOUND.ordinal()] = 7;
        c[gcp.LAGUNA_SOUND.ordinal()] = 8;
        c[gcp.MALIBU_SOUND.ordinal()] = 9;
        c[gcp.LAGUNAHD_SOUND.ordinal()] = 10;
        c[gcp.NEWPORT_SOUND.ordinal()] = 11;
        c[gcp.LAGUNA_NO_SOUND.ordinal()] = 12;
        c[gcp.MALIBU_NO_SOUND.ordinal()] = 13;
        c[gcp.LAGUNAHD_NO_SOUND.ordinal()] = 14;
        c[gcp.NEWPORT_NO_SOUND.ordinal()] = 15;
        c[gcp.AUDIO_STITCH.ordinal()] = 16;
        c[gcp.FRIEND_DEPRECATED.ordinal()] = 17;
        c[gcp.BLOB.ordinal()] = 18;
        c[gcp.GIF.ordinal()] = 19;
        c[gcp.FINGERPRINT_HEADER_SIZE.ordinal()] = 20;
        c[gcp.UNKNOWN.ordinal()] = 21;
        iArr = new int[gcp.values().length];
        d = iArr;
        iArr[gcp.AUDIO.ordinal()] = 1;
        d[gcp.VIDEO.ordinal()] = 2;
        d[gcp.LAGUNA_SOUND.ordinal()] = 3;
        d[gcp.MALIBU_SOUND.ordinal()] = 4;
        d[gcp.LAGUNAHD_SOUND.ordinal()] = 5;
        d[gcp.NEWPORT_SOUND.ordinal()] = 6;
        d[gcp.AUDIO_STITCH.ordinal()] = 7;
        d[gcp.IMAGE.ordinal()] = 8;
        d[gcp.PSYCHOMANTIS.ordinal()] = 9;
        d[gcp.SCREAMINGMANTIS.ordinal()] = 10;
        d[gcp.GHOSTMANTIS.ordinal()] = 11;
        d[gcp.VIDEO_NO_SOUND.ordinal()] = 12;
        d[gcp.LAGUNA_NO_SOUND.ordinal()] = 13;
        d[gcp.MALIBU_NO_SOUND.ordinal()] = 14;
        d[gcp.LAGUNAHD_NO_SOUND.ordinal()] = 15;
        d[gcp.NEWPORT_NO_SOUND.ordinal()] = 16;
        d[gcp.FRIEND_DEPRECATED.ordinal()] = 17;
        d[gcp.BLOB.ordinal()] = 18;
        d[gcp.GIF.ordinal()] = 19;
        d[gcp.FINGERPRINT_HEADER_SIZE.ordinal()] = 20;
        d[gcp.UNKNOWN.ordinal()] = 21;
        iArr = new int[gcp.values().length];
        e = iArr;
        iArr[gcp.LAGUNA_SOUND.ordinal()] = 1;
        e[gcp.MALIBU_SOUND.ordinal()] = 2;
        e[gcp.LAGUNAHD_SOUND.ordinal()] = 3;
        e[gcp.NEWPORT_SOUND.ordinal()] = 4;
        e[gcp.LAGUNA_NO_SOUND.ordinal()] = 5;
        e[gcp.MALIBU_NO_SOUND.ordinal()] = 6;
        e[gcp.LAGUNAHD_NO_SOUND.ordinal()] = 7;
        e[gcp.NEWPORT_NO_SOUND.ordinal()] = 8;
        e[gcp.PSYCHOMANTIS.ordinal()] = 9;
        e[gcp.SCREAMINGMANTIS.ordinal()] = 10;
        e[gcp.GHOSTMANTIS.ordinal()] = 11;
        e[gcp.AUDIO.ordinal()] = 12;
        e[gcp.AUDIO_STITCH.ordinal()] = 13;
        e[gcp.VIDEO.ordinal()] = 14;
        e[gcp.IMAGE.ordinal()] = 15;
        e[gcp.VIDEO_NO_SOUND.ordinal()] = 16;
        e[gcp.FRIEND_DEPRECATED.ordinal()] = 17;
        e[gcp.BLOB.ordinal()] = 18;
        e[gcp.GIF.ordinal()] = 19;
        e[gcp.FINGERPRINT_HEADER_SIZE.ordinal()] = 20;
        e[gcp.UNKNOWN.ordinal()] = 21;
        iArr = new int[gcp.values().length];
        f = iArr;
        iArr[gcp.MALIBU_SOUND.ordinal()] = 1;
        f[gcp.MALIBU_NO_SOUND.ordinal()] = 2;
        f[gcp.SCREAMINGMANTIS.ordinal()] = 3;
        iArr = new int[gcp.values().length];
        g = iArr;
        iArr[gcp.NEWPORT_SOUND.ordinal()] = 1;
        g[gcp.NEWPORT_NO_SOUND.ordinal()] = 2;
        g[gcp.GHOSTMANTIS.ordinal()] = 3;
        iArr = new int[gcp.values().length];
        h = iArr;
        iArr[gcp.LAGUNAHD_NO_SOUND.ordinal()] = 1;
        h[gcp.LAGUNA_NO_SOUND.ordinal()] = 2;
        h[gcp.LAGUNAHD_SOUND.ordinal()] = 3;
        h[gcp.LAGUNA_SOUND.ordinal()] = 4;
        h[gcp.PSYCHOMANTIS.ordinal()] = 5;
        iArr = new int[gcp.values().length];
        i = iArr;
        iArr[gcp.IMAGE.ordinal()] = 1;
        i[gcp.VIDEO.ordinal()] = 2;
        i[gcp.VIDEO_NO_SOUND.ordinal()] = 3;
        i[gcp.FRIEND_DEPRECATED.ordinal()] = 4;
        i[gcp.BLOB.ordinal()] = 5;
        i[gcp.LAGUNA_SOUND.ordinal()] = 6;
        i[gcp.LAGUNA_NO_SOUND.ordinal()] = 7;
        i[gcp.GIF.ordinal()] = 8;
        i[gcp.FINGERPRINT_HEADER_SIZE.ordinal()] = 9;
        i[gcp.AUDIO_STITCH.ordinal()] = 10;
        i[gcp.PSYCHOMANTIS.ordinal()] = 11;
        i[gcp.SCREAMINGMANTIS.ordinal()] = 12;
        i[gcp.MALIBU_SOUND.ordinal()] = 13;
        i[gcp.MALIBU_NO_SOUND.ordinal()] = 14;
        i[gcp.LAGUNAHD_SOUND.ordinal()] = 15;
        i[gcp.LAGUNAHD_NO_SOUND.ordinal()] = 16;
        i[gcp.GHOSTMANTIS.ordinal()] = 17;
        i[gcp.NEWPORT_SOUND.ordinal()] = 18;
        i[gcp.NEWPORT_NO_SOUND.ordinal()] = 19;
        i[gcp.AUDIO.ordinal()] = 20;
        i[gcp.UNKNOWN.ordinal()] = 21;
    }
}
