package defpackage;

/* renamed from: iio */
public final /* synthetic */ class iio {
    public static final /* synthetic */ int[] a;
    public static final /* synthetic */ int[] b;
    public static final /* synthetic */ int[] c;
    public static final /* synthetic */ int[] d;
    public static final /* synthetic */ int[] e;
    public static final /* synthetic */ int[] f;
    public static final /* synthetic */ int[] g;
    public static final /* synthetic */ int[] h;
    public static final /* synthetic */ int[] i;
    public static final /* synthetic */ int[] j;
    public static final /* synthetic */ int[] k;
    private static /* synthetic */ int[] l;

    static {
        int[] iArr = new int[iin.values().length];
        a = iArr;
        iArr[iin.SNAP_RECEIVED_AND_NOT_VIEWED_SOUND.ordinal()] = 1;
        a[iin.SNAP_RECEIVED_AND_NOT_LOADED_SOUND.ordinal()] = 2;
        a[iin.SNAP_RECEIVED_AND_NOT_VIEWED_BIRTHDAY_SOUND.ordinal()] = 3;
        a[iin.SNAP_RECEIVED_AND_NOT_LOADED_BIRTHDAY_SOUND.ordinal()] = 4;
        iArr = new int[iin.values().length];
        b = iArr;
        iArr[iin.SNAP_RECEIVED_AND_NOT_VIEWED_NO_SOUND.ordinal()] = 1;
        b[iin.SNAP_RECEIVED_AND_NOT_LOADED_NO_SOUND.ordinal()] = 2;
        b[iin.SNAP_RECEIVED_AND_NOT_VIEWED_BIRTHDAY_NO_SOUND.ordinal()] = 3;
        b[iin.SNAP_RECEIVED_AND_NOT_LOADED_BIRTHDAY_NO_SOUND.ordinal()] = 4;
        iArr = new int[iin.values().length];
        c = iArr;
        iArr[iin.SNAP_RECEIVED_AND_VIEWED_SOUND.ordinal()] = 1;
        c[iin.SNAP_VIEWED_AND_REPLAY_AVAILABLE_SOUND.ordinal()] = 2;
        c[iin.SNAP_RECEIVED_AND_REPLAYED_SOUND.ordinal()] = 3;
        c[iin.SNAP_RECEIVED_AND_SCREENSHOTTED_SOUND.ordinal()] = 4;
        c[iin.SNAP_RECEIVED_AND_SCREEN_RECORDED_SOUND.ordinal()] = 5;
        c[iin.SNAP_RECEIVED_AND_REPLAYED_AND_SCREENSHOTTED_SOUND.ordinal()] = 6;
        c[iin.SNAP_RECEIVED_AND_REPLAYED_AND_SCREEN_RECORDED_SOUND.ordinal()] = 7;
        iArr = new int[iin.values().length];
        d = iArr;
        iArr[iin.SNAP_RECEIVED_AND_VIEWED_NO_SOUND.ordinal()] = 1;
        d[iin.SNAP_VIEWED_AND_REPLAY_AVAILABLE_NO_SOUND.ordinal()] = 2;
        d[iin.SNAP_RECEIVED_AND_REPLAYED_NO_SOUND.ordinal()] = 3;
        d[iin.SNAP_RECEIVED_AND_SCREENSHOTTED_NO_SOUND.ordinal()] = 4;
        d[iin.SNAP_RECEIVED_AND_REPLAYED_AND_SCREENSHOTTED_NO_SOUND.ordinal()] = 5;
        d[iin.SNAP_RECEIVED_AND_SCREEN_RECORDED_NO_SOUND.ordinal()] = 6;
        d[iin.SNAP_RECEIVED_AND_REPLAYED_AND_SCREEN_RECORDED_NO_SOUND.ordinal()] = 7;
        iArr = new int[iin.values().length];
        e = iArr;
        iArr[iin.SNAP_SENDING.ordinal()] = 1;
        e[iin.CHAT_SENDING.ordinal()] = 2;
        iArr = new int[iin.values().length];
        l = iArr;
        iArr[iin.FAILED.ordinal()] = 1;
        l[iin.FAILED_NON_RECOVERABLE.ordinal()] = 2;
        l[iin.WAITING_TO_SEND.ordinal()] = 3;
        iArr = new int[iin.values().length];
        f = iArr;
        iArr[iin.CHAT_RECEIVED.ordinal()] = 1;
        f[iin.CHAT_ADDED.ordinal()] = 2;
        f[iin.CHAT_RENAMED.ordinal()] = 3;
        f[iin.CHAT_WELCOME.ordinal()] = 4;
        f[iin.CHAT_MEDIA_SAVE_RECEIVED.ordinal()] = 5;
        f[iin.GROUP_CREATED.ordinal()] = 6;
        f[iin.GROUP_MEMBER_JOINED.ordinal()] = 7;
        f[iin.GROUP_NAME_UPDATED.ordinal()] = 8;
        f[iin.CHAT_BIRTHDAY_RECEIVED.ordinal()] = 9;
        f[iin.CHAT_BIRTHDAY_ADDED.ordinal()] = 10;
        f[iin.CHAT_BIRTHDAY_RENAMED.ordinal()] = 11;
        iArr = new int[iin.values().length];
        g = iArr;
        iArr[iin.CHAT_RECEIVED.ordinal()] = 1;
        g[iin.CHAT_ADDED.ordinal()] = 2;
        g[iin.CHAT_RENAMED.ordinal()] = 3;
        g[iin.CHAT_WELCOME.ordinal()] = 4;
        g[iin.CHAT_SCREENSHOT.ordinal()] = 5;
        g[iin.CHAT_MEDIA_SAVE_RECEIVED.ordinal()] = 6;
        g[iin.GROUP_CREATED.ordinal()] = 7;
        g[iin.GROUP_MEMBER_JOINED.ordinal()] = 8;
        g[iin.GROUP_NAME_UPDATED.ordinal()] = 9;
        g[iin.CHAT_BIRTHDAY_RECEIVED.ordinal()] = 10;
        g[iin.CHAT_BIRTHDAY_ADDED.ordinal()] = 11;
        g[iin.CHAT_BIRTHDAY_RENAMED.ordinal()] = 12;
        g[iin.MISSED_AUDIO_CALL_RECEIVED_AND_NOT_VIEWED.ordinal()] = 13;
        g[iin.MISSED_VIDEO_CALL_RECEIVED_AND_NOT_VIEWED.ordinal()] = 14;
        iArr = new int[iin.values().length];
        h = iArr;
        iArr[iin.CHAT_SENT_AND_OPENED.ordinal()] = 1;
        h[iin.CASH_SENT_AND_OPENED.ordinal()] = 2;
        h[iin.SNAP_SENT_AND_SCREENSHOTTED_SOUND.ordinal()] = 3;
        h[iin.SNAP_SENT_AND_SCREENSHOTTED_NO_SOUND.ordinal()] = 4;
        h[iin.SNAP_SENT_AND_SCREEN_RECORDED_SOUND.ordinal()] = 5;
        h[iin.SNAP_SENT_AND_SCREEN_RECORDED_NO_SOUND.ordinal()] = 6;
        h[iin.SNAP_SENT_AND_REPLAYED_SOUND.ordinal()] = 7;
        h[iin.SNAP_SENT_AND_REPLAYED_NO_SOUND.ordinal()] = 8;
        h[iin.SNAP_SENT_AND_REPLAYED_AND_SCREENSHOTTED_SOUND.ordinal()] = 9;
        h[iin.SNAP_SENT_AND_REPLAYED_AND_SCREENSHOTTED_NO_SOUND.ordinal()] = 10;
        h[iin.SNAP_SENT_AND_REPLAYED_AND_SCREEN_RECORDED_SOUND.ordinal()] = 11;
        h[iin.SNAP_SENT_AND_REPLAYED_AND_SCREEN_RECORDED_NO_SOUND.ordinal()] = 12;
        h[iin.SNAP_SENT_AND_OPENED_SOUND.ordinal()] = 13;
        h[iin.SNAP_SENT_AND_OPENED_NO_SOUND.ordinal()] = 14;
        h[iin.MISSED_AUDIO_CALL_SENT_AND_OPENED.ordinal()] = 15;
        h[iin.MISSED_VIDEO_CALL_SENT_AND_OPENED.ordinal()] = 16;
        h[iin.OUTGOING_AUDIO_CALL_SENT_AND_OPENED.ordinal()] = 17;
        h[iin.OUTGOING_VIDEO_CALL_SENT_AND_OPENED.ordinal()] = 18;
        iArr = new int[iin.values().length];
        i = iArr;
        iArr[iin.CHAT_SENT.ordinal()] = 1;
        i[iin.CHAT_MEDIA_SAVE_SENT.ordinal()] = 2;
        i[iin.CASH_SENT.ordinal()] = 3;
        i[iin.CONTENT_INVITE_SENT.ordinal()] = 4;
        i[iin.SNAP_SENT_SOUND.ordinal()] = 5;
        i[iin.SNAP_SENT_NO_SOUND.ordinal()] = 6;
        i[iin.MISSED_AUDIO_CALL_SENT_AND_NOT_OPENED.ordinal()] = 7;
        i[iin.MISSED_VIDEO_CALL_SENT_AND_NOT_OPENED.ordinal()] = 8;
        i[iin.OUTGOING_AUDIO_CALL_SENT_AND_NOT_OPENED.ordinal()] = 9;
        i[iin.OUTGOING_VIDEO_CALL_SENT_AND_NOT_OPENED.ordinal()] = 10;
        iArr = new int[iin.values().length];
        j = iArr;
        iArr[iin.SNAP_RECEIVED_AND_NOT_VIEWED_NO_SOUND.ordinal()] = 1;
        j[iin.SNAP_RECEIVED_AND_NOT_VIEWED_SOUND.ordinal()] = 2;
        iArr = new int[iin.values().length];
        k = iArr;
        iArr[iin.CHAT_SENDING.ordinal()] = 1;
        k[iin.SNAP_SENDING.ordinal()] = 2;
        k[iin.WAITING_TO_SEND.ordinal()] = 3;
        k[iin.FAILED_NON_RECOVERABLE.ordinal()] = 4;
        k[iin.UNKNOWN.ordinal()] = 5;
        k[iin.CHAT_WELCOME.ordinal()] = 6;
    }
}
