package defpackage;

import defpackage.ily.a;

/* renamed from: iom */
public enum iom implements ily {
    BACKUP_ERROR,
    BACKUP_TOTAL_OPERATION,
    BACKUP_PAUSED,
    BACKUP_PROCESSING,
    BACKUP_SESSION_ERROR,
    BACKUP_SKIP_OPERATIONS,
    BACKUP_THUMBNAIL_ERROR,
    BACKUP_TRIGGER_RESYNC,
    BACKUP_UPLOAD,
    CONTENT_LOAD,
    CONTENT_LOAD_ERROR,
    CONTENT_LOAD_SKIP_LOCKED,
    CONTENT_STEP_LATENCY,
    ACTION_MENU_MISSING_ENTRY,
    MIGRATE_ATTEMPT,
    MIGRATE_ERRORS,
    MIGRATE_INVALID_ROW,
    MIGRATE_CONVERT_ERROR,
    MIGRATE_TOTAL_OPS,
    MIGRATE_MIGRATED_OPS,
    DB_MISSING_TABLE,
    MIGRATE_ATTEMPT_FILE,
    MIGRATE_ERROR_FILE,
    MIGRATE_MIGRATED_FILE,
    MIGRATE_FILE_TYPE,
    MIGRATE_TOTAL_FILE,
    MIGRATE_FM_REMOVE_ATTEMPT,
    MIGRATE_FM_REMOVE_RESULT,
    MIGRATE_FM_REMOVE_ERROR,
    MIGRATE_MEO_ATTEMPT,
    MIGRATE_MEO_DB_READ,
    MIGRATE_MEO_KEY_AVAILABLE,
    MIGRATE_MEO_KEY_STORED,
    MIGRATE_MEO_DB_KEY_MISSING,
    MIGRATE_MEO_DB_UNLOCK,
    MIGRATE_MEO_USER_ID_MISSING,
    MIGRATE_MEO_LIB_LOAD,
    MEO_SYNC_ATTEMPT,
    MEO_SYNC_BLOCKED,
    MEO_SYNC_MISMATCH,
    MEO_SYNC_RESULT,
    MEO_SYNC_ERROR,
    MEO_SYNC_STEP,
    LOGIN_PURGE_RESULT,
    LOGIN_PURGE_QUERY,
    INITIAL_SYNC,
    INITIAL_SYNC_STEP_LATENCY,
    INITIAL_SYNC_NETWORK_LATENCY,
    SYNC_ERROR,
    SYNC_INVALID_STATE,
    SYNC_TRIGGER_FORCE_RESYNC,
    SAVE_START,
    SAVE_ATTEMPT,
    EDIT_ATTEMPT,
    SAVE_MISSING_EDITS,
    SAVE_PERCEIVED_LATENCY,
    SAVE_STEP_LATENCY,
    SAVE_RESULT,
    SAVE_ERROR,
    SAVE_ELIGIBLE_FOR_STREAMING,
    TRANSCODING_TIME_IN_QUEUE,
    TRANSCODING_SUCCESS,
    TRANSCODING_SKIP,
    TRANSCODING_FAILURE,
    TRANSCODING_JOB_RESULT,
    TRANSCODING_INITIAL_QUERY_FAIL,
    TRANSCODING_DISK_SPACE_STATUS,
    TRANSCODING_MEDIA_PACKAGE_SOURCE,
    TRANSCODING_POST_TRANSCODE_FAIL,
    TRANSCODING_PLACEHOLDER_FAIL,
    TRANSCODING_FAILED_TO_IMPORT,
    TRANSCODING_CRITICAL_FAILURE,
    TRANSCODING_FALLBACK_FAILURE,
    THUMBNAIL_SUCCESS,
    THUMBNAIL_FAILURE,
    THUMBNAIL_TOTAL_LATENCY,
    THUMBNAIL_QUEUE_LATENCY,
    THUMBNAIL_DATA_SOURCE_LATENCY,
    THUMBNAIL_DECODE_LATENCY,
    THUMBNAIL_SIZE,
    MEO_MOVE,
    MEO_UNLOCK,
    MEO_UNLOCK_EXCEPTION,
    MEO_UNLOCK_GET_ASSERTION,
    MEO_UNLOCK_RETRIEVE_MASTER_KEY,
    MEO_BATCH_DECRYPT,
    MEO_BATCH_DECRYPT_SUCCESS_RATE,
    MEO_DECRYPT,
    MEO_IMPORT_ATTEMPT,
    MEO_IMPORT,
    UPLOAD_RESULT,
    DMPD_RESULT,
    DMPD_ERROR;

    public final ilz a(String str, Enum<?> enumR) {
        akcr.b(str, "shortKey");
        akcr.b(enumR, "shortValue");
        return a.a((ily) this, str, (Enum) enumR);
    }

    public final ilz a(String str, String str2) {
        akcr.b(str, "shortKey");
        akcr.b(str2, "shortValue");
        return a.a((ily) this, str, str2);
    }

    public final ilz a(String str, boolean z) {
        akcr.b(str, "shortKey");
        return a.a((ily) this, str, z);
    }

    public final ink a() {
        return ink.MEMORIES;
    }

    public final ilz b() {
        return a.a(this);
    }
}
