package defpackage;

import defpackage.fth.a;
import java.util.EnumSet;
import java.util.concurrent.TimeUnit;

/* renamed from: mja */
public enum mja implements mje {
    CAMERA_LENSES_ACTIVATED(a.a(false), mje.a.READ_WRITE),
    CAMERA_LENS_DEACTIVATE_ON_CLOSE(a.a(true), mje.a.READ_ONLY),
    CAMERA_LENS_BLUE_BADGES(a.a(true), mje.a.READ_ONLY),
    CAMERA_ONBOARDING_CAROUSEL_SWIPE_TOOLTIP_SHOWN(a.a(false), mje.a.READ_WRITE),
    CAMERA_ONBOARDING_CAROUSEL_CAPTURE_TOOLTIP_SHOWN(a.a(false), mje.a.READ_WRITE),
    CAMERA_ONBOARINDG_CAPTURE_TOOLTIP_SHOWN(a.a(false), mje.a.READ_ONLY),
    LENSES_ONBOARDING_TOOLTIP_ENABLED(a.a(true), mje.a.READ_ONLY),
    CAMERA_CAROUSEL_SWITCH_SCHEDULE(a.a(true), mje.a.READ_ONLY),
    CAMERA_LEFT_CAROUSEL_SUPPORT(a.a(true), mje.a.READ_ONLY),
    CAMERA_CAROUSEL_FAKE_ITEMS(a.a(true), mje.a.READ_WRITE),
    LENSES_DEBUG_MODE(a.a(miz.DEFAULT), mje.a.READ_WRITE),
    CAMERA_LENS_LOCKING_ENABLED(a.a(false), mje.a.READ_ONLY),
    TRACKING_DATA_NAME(a.a("TrackingData_7D2DD425BDE6A9F4304EDEEFC0E62C011C42983F04B0E3F44465107737AA0B12"), mje.a.READ_ONLY),
    TRACKING_DATA_CHECKSUM(a.a("148EDBD42A6D60061CFAA8D42F304CE1833271E3F9DD7B792CB0B579D911AAD7"), mje.a.READ_ONLY),
    CONTENT_MANAGER_ENABLED(a.a(true), mje.a.READ_ONLY),
    NATIVE_LOGS_ENABLED(a.a(true), mje.a.READ_WRITE),
    DEVICE_CLUSTER(a.a(-1), mje.a.READ_ONLY),
    LENS_SCHEDULED_PROTO_CACHE_ENABLED(a.a(true), mje.a.READ_ONLY),
    LENS_SCHEDULED_PROTO_FETCH_ENABLED(a.a(false), mje.a.READ_ONLY),
    LENS_GEO_ENABLED(a.a(true), mje.a.READ_ONLY),
    LENS_UNLOCKED_ENABLED(a.a(true), mje.a.READ_ONLY),
    SPONSORED_LENS_ENABLED(a.a(true), mje.a.READ_ONLY),
    SNAPPABLE_LENSES_ENABLED(a.a(true), mje.a.READ_ONLY),
    INFO_BUTTON_FOR_ALL(a.a(false), mje.a.READ_ONLY),
    ENABLE_IMAGE_PICKER(a.a(true), mje.a.READ_WRITE),
    ENABLE_EXTERNAL_IMAGES(a.a(false), mje.a.READ_WRITE),
    UPCOMING_MESSAGE_ENABLED(a.a(true), mje.a.READ_ONLY),
    NATIVE_PROFILER_ENABLED(a.a(false), mje.a.READ_ONLY),
    CENSORED_PROMPT_ENABLED(a.a(false), mje.a.READ_ONLY),
    THIRD_PARTY_AD_TRACK_V2_URL(a.a("https://usc.adserver.snapads.com/v2/track"), mje.a.READ_ONLY),
    BITMOJI_POPUP_ENABLED(a.a(true), mje.a.READ_ONLY),
    LENS_EXPLORER_ENABLED(a.a(true), mje.a.READ_ONLY),
    LENS_EXPLORER_NATIVE_ENABLED(a.a(false), mje.a.READ_ONLY),
    LENS_EXPLORER_BADGE_SHOW_INTERVAL_MINUTES(a.a(TimeUnit.DAYS.toMinutes(1)), mje.a.READ_ONLY),
    LENS_EXPLORER_BADGE_LAST_TIME_SHOWN_MILLIS(a.a(0), mje.a.READ_WRITE),
    LENS_EXPLORER_MOCK_SUBSCRIPTIONS(a.a(false), mje.a.READ_ONLY),
    LENS_EXPLORER_TOOLTIP_SHOWN_TIMES_MAX(a.a(1), mje.a.READ_ONLY),
    LENS_EXPLORER_TOOLTIP_ENABLED(a.a(false), mje.a.READ_WRITE),
    LENS_EXPLORER_ENABLE_CREATOR_PROFILE(a.a(false), mje.a.READ_ONLY),
    LENS_EXPLORER_OVERRIDE_CREATOR_PROFILE_ID(a.a(false), mje.a.READ_ONLY),
    LENSES_FOREGROUND_PREFETCH_ENABLED(a.a(false), mje.a.READ_ONLY),
    LENSES_FOREGROUND_PREFETCH_RUN_IN_BACKGROUND(a.a(true), mje.a.READ_ONLY),
    LENSES_BACKGROUND_PREFETCH_ENABLED(a.a(false), mje.a.READ_ONLY),
    LENSES_BACKGROUND_PREFETCH_DELAY_MINUTES(a.a(-1), mje.a.READ_ONLY),
    LENSES_BACKGROUND_PREFETCH_AFTER_MIDNIGHT_JITTER_MINUTES(a.a(-1), mje.a.READ_ONLY),
    LENSES_BACKGROUND_PREFETCH_NUM_RETRIES(a.a(0), mje.a.READ_ONLY),
    LENSES_BACKGROUND_PREFETCH_TIMEOUT_MINUTES(a.a(5), mje.a.READ_ONLY),
    LENSES_ACTIVE_USER_EXPIRATION_TIME_IN_MINUTES(a.a(-1), mje.a.READ_ONLY),
    LENSES_ACTIVE_USER_LAST_ACTIVATION(a.a(-1), mje.a.READ_WRITE),
    ENABLE_EDGE_CACHE_STORY_DOWNLOADS(a.a(false), mje.a.READ_ONLY),
    DEACTIVATE_LENSES_AFTER_SNAP_SEND(a.a(false), mje.a.READ_ONLY),
    IMAGE_RESOLUTION_DEVICE_CLUSTER_ENABLED(a.a(false), mje.a.READ_ONLY),
    IMAGE_RESOLUTION_DEVICE_CLUSTER_LOW_END_START(a.a(1), mje.a.READ_ONLY),
    IMAGE_RESOLUTION_DEVICE_CLUSTER_MID_END_START(a.a(4), mje.a.READ_ONLY),
    IMAGE_RESOLUTION_DEVICE_CLUSTER_HIGH_END_START(a.a(5), mje.a.READ_ONLY),
    IMAGE_RESOLUTION_DEVICE_CLUSTER_SERVER_UNKNOWN(a.a(3), mje.a.READ_ONLY),
    FEATURE_GATING_DEVICE_CLUSTER_ENABLED(a.a(false), mje.a.READ_ONLY),
    FEATURE_GATING_DEVICE_CLUSTER_LOW_END_START(a.a(1), mje.a.READ_ONLY),
    FEATURE_GATING_DEVICE_CLUSTER_MID_END_START(a.a(4), mje.a.READ_ONLY),
    FEATURE_GATING_DEVICE_CLUSTER_HIGH_END_START(a.a(5), mje.a.READ_ONLY),
    FEATURE_GATING_DEVICE_CLUSTER_SERVER_UNKNOWN(a.a(3), mje.a.READ_ONLY),
    FORCE_TO_USE_SW_RECORDING(a.a(false), mje.a.READ_ONLY),
    MOVE_SPONSORED_GEO_LENSES_TO_BACK(a.a(false), mje.a.READ_ONLY),
    LENSES_WEATHER_DATA_ENABLED(a.a(true), mje.a.READ_ONLY),
    LENSES_WEATHER_BASE_URL_KEY(a.a("https://weather.sc-jpl.com/weatherservice"), mje.a.READ_ONLY),
    LENSES_RETAIN_LENS_ASSETS(a.a(false), mje.a.READ_ONLY),
    LENS_PROCESSING_ASYNC_TRACKING_ANDROID_ASYNC_TRACKING_ENABLED(a.a("true"), mje.a.READ_ONLY),
    LENS_PROCESSING_ASYNC_TRACKING_ANDROID_ASYNC_TEXREAD_ENABLED(a.a("false"), mje.a.READ_ONLY),
    LENSCORE_HIGH_ACCURACY_FACE_DETECTION_RETRY_TIME(a.a("0.0"), mje.a.READ_ONLY),
    LENSCORE_HIGH_ACCURACY_FACE_DETECTION_LOAD_PRIORITY(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_HIGH_ACCURACY_FACE_DETECTION_MODE(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_TICKS_HE_ANDROID_MULTIPLIER(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_TICKS_ME_ANDROID_MULTIPLIER(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_TICKS_LE_ANDROID_MULTIPLIER(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_TIME_HE_ANDROID_MULTIPLIER(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_TIME_ME_ANDROID_MULTIPLIER(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_TIME_LE_ANDROID_MULTIPLIER(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_TIMES_MILLIS(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_STATES_COUNT(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SECOND_FACE_DETECTION_THROTTLE_TICKS(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_FRAMEBUFFER_FETCH_WHITELIST(a.a("use blacklist"), mje.a.READ_ONLY),
    LENSCORE_ASYNC_MIPMAP(a.a("kAsyncMipmapABTestSync"), mje.a.READ_ONLY),
    LENSCORE_SNAPPABLES_CONTEXT_R1(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SNAPPABLES_CONTEXT_R2(a.a(r3), mje.a.READ_ONLY),
    LENSCORE_SNAPPABLES_CONTEXT_R3(a.a(r3), mje.a.READ_ONLY),
    CLEAR_LENS_PERSISTENT_STORE_SETTINGS_OPTION(a.a(true), mje.a.READ_ONLY);
    
    private final a<?> delegate;
    private final EnumSet<mje.a> permissions;

    private mja(a<?> aVar, EnumSet<mje.a> enumSet) {
        this.delegate = aVar;
        this.permissions = enumSet;
    }

    public final a<?> a() {
        return this.delegate;
    }

    public final ftg b() {
        return ftg.LENSES;
    }

    public final EnumSet<mje.a> c() {
        return this.permissions;
    }
}
