package defpackage;

/* renamed from: rdu */
public final /* synthetic */ class rdu {
    public static final /* synthetic */ int[] a;
    public static final /* synthetic */ int[] b;

    static {
        int[] iArr = new int[iin.values().length];
        a = iArr;
        iArr[iin.SNAP_RECEIVED_AND_NOT_VIEWED_SOUND.ordinal()] = 1;
        a[iin.SNAP_RECEIVED_AND_NOT_VIEWED_NO_SOUND.ordinal()] = 2;
        iArr = new int[iin.values().length];
        b = iArr;
        iArr[iin.CHAT_SENDING.ordinal()] = 1;
        b[iin.SNAP_SENDING.ordinal()] = 2;
        b[iin.PENDING.ordinal()] = 3;
        b[iin.WAITING_TO_SEND.ordinal()] = 4;
        b[iin.FAILED.ordinal()] = 5;
        b[iin.FAILED_NON_RECOVERABLE.ordinal()] = 6;
        b[iin.SNAP_SENT_SOUND.ordinal()] = 7;
        b[iin.SNAP_SENT_NO_SOUND.ordinal()] = 8;
        b[iin.CHAT_SENT.ordinal()] = 9;
        b[iin.CASH_SENT.ordinal()] = 10;
        b[iin.OUTGOING_AUDIO_CALL_SENT_AND_NOT_OPENED.ordinal()] = 11;
        b[iin.OUTGOING_VIDEO_CALL_SENT_AND_NOT_OPENED.ordinal()] = 12;
        b[iin.SNAP_RECEIVED_AND_REPLAYED_AND_SCREENSHOTTED_SOUND.ordinal()] = 13;
        b[iin.SNAP_RECEIVED_AND_REPLAYED_AND_SCREENSHOTTED_NO_SOUND.ordinal()] = 14;
        b[iin.SNAP_RECEIVED_AND_SCREENSHOTTED_SOUND.ordinal()] = 15;
        b[iin.SNAP_RECEIVED_AND_SCREENSHOTTED_NO_SOUND.ordinal()] = 16;
        b[iin.SNAP_SENT_AND_REPLAYED_AND_SCREENSHOTTED_SOUND.ordinal()] = 17;
        b[iin.SNAP_SENT_AND_REPLAYED_AND_SCREENSHOTTED_NO_SOUND.ordinal()] = 18;
        b[iin.SNAP_SENT_AND_SCREENSHOTTED_SOUND.ordinal()] = 19;
        b[iin.SNAP_SENT_AND_SCREENSHOTTED_NO_SOUND.ordinal()] = 20;
        b[iin.SNAP_RECEIVED_AND_REPLAYED_AND_SCREEN_RECORDED_SOUND.ordinal()] = 21;
        b[iin.SNAP_RECEIVED_AND_REPLAYED_AND_SCREEN_RECORDED_NO_SOUND.ordinal()] = 22;
        b[iin.SNAP_RECEIVED_AND_SCREEN_RECORDED_SOUND.ordinal()] = 23;
        b[iin.SNAP_RECEIVED_AND_SCREEN_RECORDED_NO_SOUND.ordinal()] = 24;
        b[iin.SNAP_SENT_AND_REPLAYED_AND_SCREEN_RECORDED_SOUND.ordinal()] = 25;
        b[iin.SNAP_SENT_AND_REPLAYED_AND_SCREEN_RECORDED_NO_SOUND.ordinal()] = 26;
        b[iin.SNAP_SENT_AND_SCREEN_RECORDED_SOUND.ordinal()] = 27;
        b[iin.SNAP_SENT_AND_SCREEN_RECORDED_NO_SOUND.ordinal()] = 28;
        b[iin.SNAP_RECEIVED_AND_REPLAYED_SOUND.ordinal()] = 29;
        b[iin.SNAP_RECEIVED_AND_REPLAYED_NO_SOUND.ordinal()] = 30;
        b[iin.SNAP_SENT_AND_REPLAYED_SOUND.ordinal()] = 31;
        b[iin.SNAP_SENT_AND_REPLAYED_NO_SOUND.ordinal()] = 32;
        b[iin.SNAP_SENT_AND_OPENED_NO_SOUND.ordinal()] = 33;
        b[iin.SNAP_SENT_AND_OPENED_SOUND.ordinal()] = 34;
        b[iin.CHAT_SENT_AND_OPENED.ordinal()] = 35;
        b[iin.CASH_SENT_AND_OPENED.ordinal()] = 36;
        b[iin.OUTGOING_AUDIO_CALL_SENT_AND_OPENED.ordinal()] = 37;
        b[iin.OUTGOING_VIDEO_CALL_SENT_AND_OPENED.ordinal()] = 38;
        b[iin.SNAP_RECEIVED_AND_VIEWED_SOUND.ordinal()] = 39;
        b[iin.SNAP_RECEIVED_AND_VIEWED_NO_SOUND.ordinal()] = 40;
        b[iin.SNAP_VIEWED_AND_REPLAY_AVAILABLE_SOUND.ordinal()] = 41;
        b[iin.SNAP_VIEWED_AND_REPLAY_AVAILABLE_NO_SOUND.ordinal()] = 42;
        b[iin.CHAT_RECEIVED_AND_VIEWED.ordinal()] = 43;
        b[iin.CASH_RECEIVED_AND_VIEWED.ordinal()] = 44;
        b[iin.INCOMING_AUDIO_CALL_RECEIVED_AND_VIEWED.ordinal()] = 45;
        b[iin.INCOMING_VIDEO_CALL_RECEIVED_AND_VIEWED.ordinal()] = 46;
        b[iin.CHAT_WELCOME.ordinal()] = 47;
        b[iin.CHAT_RECEIVED.ordinal()] = 48;
        b[iin.CHAT_BIRTHDAY_RECEIVED.ordinal()] = 49;
        b[iin.CASH_RECEIVED.ordinal()] = 50;
        b[iin.INCOMING_AUDIO_CALL_RECEIVED_AND_NOT_VIEWED.ordinal()] = 51;
        b[iin.INCOMING_VIDEO_CALL_RECEIVED_AND_NOT_VIEWED.ordinal()] = 52;
        b[iin.CHAT_ADD.ordinal()] = 53;
        b[iin.CHAT_ADD_AND_OPENED.ordinal()] = 54;
        b[iin.CHAT_ADDED.ordinal()] = 55;
        b[iin.CHAT_ADDED_AND_VIEWED.ordinal()] = 56;
        b[iin.GROUP_MEMBER_JOINED.ordinal()] = 57;
        b[iin.CHAT_BIRTHDAY_ADDED.ordinal()] = 58;
        b[iin.GROUP_CREATED.ordinal()] = 59;
        b[iin.CHAT_RENAME.ordinal()] = 60;
        b[iin.GROUP_NAME_UPDATED.ordinal()] = 61;
        b[iin.CHAT_RENAME_AND_OPENED.ordinal()] = 62;
        b[iin.CHAT_RENAMED.ordinal()] = 63;
        b[iin.CHAT_RENAMED_AND_VIEWED.ordinal()] = 64;
        b[iin.CHAT_BIRTHDAY_RENAMED.ordinal()] = 65;
        b[iin.CHAT_SCREENSHOT.ordinal()] = 66;
        b[iin.CHAT_SCREENSHOT_AND_OPEN.ordinal()] = 67;
        b[iin.CHAT_MEDIA_SAVE_RECEIVED.ordinal()] = 68;
        b[iin.CHAT_MEDIA_SAVE_RECEIVED_AND_OPEN.ordinal()] = 69;
        b[iin.CHAT_MEDIA_SAVE_SENT.ordinal()] = 70;
        b[iin.MISSED_AUDIO_CALL_RECEIVED_AND_NOT_VIEWED.ordinal()] = 71;
        b[iin.MISSED_AUDIO_CALL_RECEIVED_AND_VIEWED.ordinal()] = 72;
        b[iin.MISSED_VIDEO_CALL_RECEIVED_AND_NOT_VIEWED.ordinal()] = 73;
        b[iin.MISSED_VIDEO_CALL_RECEIVED_AND_VIEWED.ordinal()] = 74;
        b[iin.MISSED_AUDIO_CALL_SENT_AND_NOT_OPENED.ordinal()] = 75;
        b[iin.MISSED_AUDIO_CALL_SENT_AND_OPENED.ordinal()] = 76;
        b[iin.MISSED_VIDEO_CALL_SENT_AND_NOT_OPENED.ordinal()] = 77;
        b[iin.MISSED_VIDEO_CALL_SENT_AND_OPENED.ordinal()] = 78;
    }
}
