package defpackage;

/* renamed from: uaj */
public enum uaj {
    MULTI_SNAP_DELETION,
    SOUND_TOOLS,
    NEW_USER,
    NEW_USER_NO_LENS,
    SWIPE_FILTER,
    FACE_CUT,
    VIDEO_TIMER,
    RESIZE_BRUSH,
    PINNABLE_STICKER,
    SAVE_BUTTON,
    HOMETAB,
    UNLOCKABLE_STICKER,
    ANIMATED_STICKER,
    SNAP_CROP,
    SNAP_CROP_TEACHING,
    GIPHY_STICKER,
    RATING_STICKER,
    FACE_CRAFT,
    MULTI_SNAP_SPLITTING,
    MULTI_SNAP_TRIMMING,
    POST_STORY_DIALOG,
    FACE_CUT_OVERLAY,
    NEW_USER_CAPTION,
    NEW_USER_DRAW,
    NEW_USER_STICKER,
    NEW_USER_FACECRAFT,
    UNDEFINED
}
