package defpackage;

/* renamed from: vjm */
public enum vjm {
    DEFAULT,
    SPECTACLES_CIRCLE_WHITE,
    SPECTACLES_CIRCLE_BLACK,
    SPECTACLES_SQUARE,
    SPECTACLES_HORIZONTAL_4_3,
    SPECTACLES_HORIZONTAL_16_9,
    SPECTACLES_PORTRAIT_9_16,
    SPECTACLES_NEWPORT
}
