package defpackage;

import android.app.Activity;
import android.content.Context;
import java.util.concurrent.atomic.AtomicBoolean;
import org.greenrobot.eventbus.ThreadMode;

/* renamed from: way */
public final class way implements ajej {
    private final ajxe a;
    private final ajei b = new ajei();
    private AtomicBoolean c = new AtomicBoolean(false);
    private final Context d;
    private final wdl e;
    private final wdd f;
    private final wcy g;
    private final wdn h;
    private final wdf i;
    private final wdg j;
    private final wde k;
    private final wdh l;
    private final wdi m;
    private final wdk n;
    private final wdj o;
    private final wdm p;
    private final wdc q;
    private final wdo r;
    private final wdq s;
    private final wdp t;
    private final wdr u;
    private final wdb v;
    private final wda w;

    /* renamed from: way$a */
    static final class a extends akcq implements akbk<vzn> {
        a(ajwy ajwy) {
            super(0, ajwy);
        }

        public final String getName() {
            return "get";
        }

        public final akej getOwner() {
            return akde.a(ajwy.class);
        }

        public final String getSignature() {
            return "get()Ljava/lang/Object;";
        }

        public final /* synthetic */ Object invoke() {
            return (vzn) ((ajwy) this.receiver).get();
        }
    }

    static {
        new aken[1][0] = new akdc(akde.a(way.class), "searchEventObserver", "getSearchEventObserver()Lcom/snap/search/framework/SearchEventObserver;");
    }

    public way(Context context, ajwy<vzn> ajwy, wdl wdl, wdd wdd, wcy wcy, wdn wdn, wdf wdf, wdg wdg, wde wde, wdh wdh, wdi wdi, wdk wdk, wdj wdj, wdm wdm, wdc wdc, wdo wdo, wdq wdq, wdp wdp, wdr wdr, wdb wdb, wda wda) {
        Context context2 = context;
        ajwy<vzn> ajwy2 = ajwy;
        wdl wdl2 = wdl;
        wdd wdd2 = wdd;
        wcy wcy2 = wcy;
        wdn wdn2 = wdn;
        wdf wdf2 = wdf;
        wdg wdg2 = wdg;
        wde wde2 = wde;
        wdh wdh2 = wdh;
        wdi wdi2 = wdi;
        wdk wdk2 = wdk;
        wdj wdj2 = wdj;
        wdm wdm2 = wdm;
        wdc wdc2 = wdc;
        wdo wdo2 = wdo;
        akcr.b(context2, "context");
        akcr.b(ajwy2, "searchEventObserverProvider");
        akcr.b(wdl2, "searchPlayStoryActionEventHandler");
        akcr.b(wdd2, "searchOpenChatActionEventHandler");
        akcr.b(wcy2, "searchAddFriendActionEventHandler");
        akcr.b(wdn2, "searchReplyCameraActionEventHandler");
        akcr.b(wdf2, "searchOpenFriendMiniProfileActionEventHandler");
        akcr.b(wdg2, "searchOpenGroupMiniProfileActionEventHandler");
        akcr.b(wde2, "searchOpenDiscoverMiniProfileActionEventHandler");
        akcr.b(wdh2, "searchOpenPublisherProfileActionEventHandler");
        akcr.b(wdi2, "searchOpenShowProfileActionEventHandler");
        akcr.b(wdk2, "searchPlayPublisherStoryActionEventHandler");
        akcr.b(wdj2, "searchPlayDynamicStoryActionEventHandler");
        akcr.b(wdm2, "searchRemoveFriendActionEventHandler");
        akcr.b(wdc2, "searchNoNetworkEventHandler");
        akcr.b(wdo, "searchSnapProOpenProfileEventHandler");
        akcr.b(wdq, "searchSnapProSubscribeEventHandler");
        akcr.b(wdp, "searchSnapProPlayStoryEventHandler");
        akcr.b(wdr, "searchStoreEventHandler");
        akcr.b(wdb, "searchMapEventHandler");
        akcr.b(wda, "searchGameEventHandler");
        wdo wdo3 = wdo;
        this.d = context2;
        this.e = wdl2;
        this.f = wdd2;
        this.g = wcy2;
        this.h = wdn2;
        this.i = wdf2;
        this.j = wdg2;
        this.k = wde2;
        this.l = wdh2;
        this.m = wdi2;
        this.n = wdk2;
        this.o = wdj2;
        this.p = wdm2;
        this.q = wdc2;
        this.r = wdo3;
        wdp wdp2 = wdp;
        this.s = wdq;
        this.t = wdp2;
        wdb wdb2 = wdb;
        this.u = wdr;
        this.v = wdb2;
        this.w = wda;
        this.a = ajxh.a(new a(ajwy));
    }

    public final void dispose() {
        this.b.dispose();
    }

    public final boolean isDisposed() {
        return this.b.isDisposed();
    }

    /*  JADX ERROR: JadxRuntimeException in pass: BlockProcessor
        jadx.core.utils.exceptions.JadxRuntimeException: Can't find immediate dominator for block B:120:0x07bb in {4, 7, 11, 12, 14, 21, 24, 27, 28, 29, 34, 35, 38, 39, 41, 42, 45, 46, 47, 50, 53, 54, 59, 60, 63, 64, 65, 68, 73, 74, 77, 80, 85, 86, 89, 92, 97, 98, 103, 104, 107, 112, 113, 116, 117, 119} preds:[]
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.computeDominators(BlockProcessor.java:242)
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.processBlocksTree(BlockProcessor.java:52)
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.visit(BlockProcessor.java:42)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
        	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
        	at java.util.ArrayList.forEach(ArrayList.java:1257)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
        	at jadx.core.ProcessClass.process(ProcessClass.java:32)
        	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:292)
        	at jadx.api.JavaClass.decompile(JavaClass.java:62)
        	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        */
    @defpackage.akqq(a = org.greenrobot.eventbus.ThreadMode.MAIN)
    public final void onSearchAction(defpackage.wbq r39) {
        /*
        r38 = this;
        r0 = r38;
        r1 = r39;
        r2 = "event";
        defpackage.akcr.b(r1, r2);
        r3 = r1 instanceof defpackage.wcm;
        r5 = 1;
        r6 = 0;
        r7 = "guardClicks";
        if (r3 == 0) goto L_0x01db;
        r3 = r0.e;
        r8 = r1;
        r8 = (defpackage.wcm) r8;
        r9 = r0.c;
        defpackage.akcr.b(r8, r2);
        defpackage.akcr.b(r9, r7);
        r2 = r3.a();
        r13 = r2.b();
        r2 = r3.a();
        r15 = r2.c();
        r2 = new ajei;
        r2.<init>();
        r7 = r8.d;
        r8 = r8.e;
        r10 = r9.compareAndSet(r6, r5);
        if (r10 != 0) goto L_0x0041;
        r2 = (defpackage.ajej) r2;
        goto L_0x0796;
        r10 = r7 instanceof defpackage.wco;
        if (r10 == 0) goto L_0x0059;
        r10 = r7;
        r10 = (defpackage.wco) r10;
        r10 = r10.b;
        r10 = java.lang.Long.valueOf(r10);
        r10 = defpackage.ajdx.b(r10);
        r11 = "Single.just(playStoryInfo.storyRowId)";
        defpackage.akcr.a(r10, r11);
        r4 = r10;
        goto L_0x009b;
        r10 = r7 instanceof defpackage.wcp;
        if (r10 == 0) goto L_0x01d5;
        r10 = r3.f;
        r10 = r10.b();
        r10 = (defpackage.yhw) r10;
        r11 = r7;
        r11 = (defpackage.wcp) r11;
        r12 = r11.b;
        r12 = defpackage.ajyl.a(r12);
        r10 = r10.a(r12);
        r12 = r3.e;
        r12 = r12.b();
        r12 = (defpackage.yhx) r12;
        r4 = new yle;
        r11 = r11.b;
        r6 = com.snap.core.db.column.StoryKind.FRIEND;
        r4.<init>(r11, r6);
        r4 = r12.a(r4);
        r4 = (defpackage.ajeb) r4;
        r4 = r10.b(r4);
        r6 = defpackage.wdl.k.a;
        r6 = (defpackage.ajfc) r6;
        r10 = r4.f(r6);
        r4 = "publicUserStorySyncer.sy…        .map { it.get() }";
        defpackage.akcr.a(r10, r4);
        goto L_0x0057;
        r6 = new slg;
        r10 = r3.k;
        r11 = new slh;
        r11.<init>();
        r11 = (defpackage.slp) r11;
        r6.<init>(r10, r11);
        r10 = r7.a;
        r10 = r10.c;
        r6.a(r10);
        r10 = new defpackage.smm[r5];
        r11 = new hak;
        r12 = r3.l;
        r5 = r3.g;
        r5 = r5.b();
        r5 = (defpackage.ajws) r5;
        r0 = "playbackEvents";
        defpackage.akcr.a(r5, r0);
        r0 = r3.a;
        r11.<init>(r12, r5, r2, r0);
        r11 = (defpackage.smm) r11;
        r0 = 0;
        r10[r0] = r11;
        r0 = defpackage.ajzt.b(r10);
        r5 = r3.i;
        r5 = r5.b();
        r5 = (defpackage.ynp) r5;
        r5 = defpackage.ynp.a.a(r5);
        r5 = (java.util.Collection) r5;
        r0.addAll(r5);
        r5 = new sti$a;
        r10 = r3.a;
        r11 = r3.b;
        r11 = r11.b();
        r22 = r11;
        r22 = (defpackage.jwa) r22;
        r11 = r3.c;
        r11 = r11.b();
        r23 = r11;
        r23 = (defpackage.jwc) r23;
        r11 = defpackage.vxc.f;
        r11 = r11.getPage();
        r24 = r11;
        r24 = (defpackage.idl) r24;
        r18 = r5;
        r19 = r0;
        r20 = r6;
        r21 = r10;
        r18.<init>(r19, r20, r21, r22, r23, r24);
        r0 = new srk;
        r6 = r7.a;
        r6 = r6.c;
        r0.<init>(r8, r6);
        r0 = (defpackage.sri) r0;
        r5.c = r0;
        r0 = r7.toString();
        r5.d = r0;
        r0 = 1;
        r5.e = r0;
        r0 = r7.a;
        r0 = r0.a;
        r5.p = r0;
        r0 = new psa;
        r6 = r7.a;
        r6 = r6.a;
        r10 = defpackage.aajy.SEARCH;
        r7 = r7.a;
        r7 = r7.b;
        r11 = 0;
        r0.<init>(r6, r10, r7, r11);
        r6 = new sks;
        r11 = r3.a();
        r7 = "playbackPerformanceAnalytics";
        defpackage.akcr.a(r11, r7);
        r12 = defpackage.aaug.TAP;
        r17 = r0;
        r17 = (defpackage.skr) r17;
        r10 = r6;
        r10.<init>(r11, r12, r13, r15, r17);
        r6 = (defpackage.ssi) r6;
        r0 = new ssi$a;
        r7 = 2;
        r7 = new defpackage.ssi[r7];
        r10 = 0;
        r7[r10] = r6;
        r6 = r3.m;
        r6 = r6.get();
        r6 = (defpackage.yhl) r6;
        r10 = r3.j;
        r10 = r10.b();
        r10 = (defpackage.ihh) r10;
        r10 = r10.a();
        r12 = defpackage.aahb.SEARCH_SF;
        r13 = r3.h;
        r13 = r13.b();
        r13 = (defpackage.fvk) r13;
        r13 = (defpackage.fvj) r13;
        r6 = r6.a(r10, r12, r13);
        r10 = 1;
        r7[r10] = r6;
        r0.<init>(r7);
        r6 = new wdl$a;
        r7 = r3.k;
        r6.<init>(r8, r7);
        r7 = r6.a;
        r8 = r6.b;
        r8 = (android.view.View) r8;
        r7.addView(r8);
        r7 = defpackage.wdl.g.a;
        r7 = (defpackage.ajfc) r7;
        r4 = r4.f(r7);
        r7 = new wdl$h;
        r7.<init>(r3, r5, r0, r9);
        r7 = (defpackage.ajfc) r7;
        r0 = r4.e(r7);
        r3 = r3.a;
        r3 = r3.l();
        r3 = (defpackage.zfr) r3;
        r3 = (defpackage.ajdw) r3;
        r0 = r0.a(r3);
        r3 = new wdl$i;
        r3.<init>(r6);
        r3 = (defpackage.ajev) r3;
        r4 = new wdl$j;
        r4.<init>(r9, r6);
        r4 = (defpackage.ajfb) r4;
        r0 = r0.a(r3, r4);
        r3 = "storyId.map {\n          …: $t\")\n                })";
        defpackage.akcr.a(r0, r3);
        defpackage.ajvv.a(r0, r2);
        r2 = (defpackage.ajej) r2;
        r0 = r38;
        goto L_0x0796;
        r0 = new ajxk;
        r0.<init>();
        throw r0;
        r0 = r1 instanceof defpackage.wby;
        if (r0 == 0) goto L_0x0235;
        r0 = r38;
        r3 = r0.f;
        r4 = r1;
        r4 = (defpackage.wby) r4;
        r5 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r5, r7);
        r2 = new ajei;
        r2.<init>();
        r6 = 1;
        r7 = 0;
        r6 = r5.compareAndSet(r7, r6);
        if (r6 == 0) goto L_0x003d;
        r4 = r4.d;
        r6 = r4 instanceof defpackage.wbz;
        if (r6 == 0) goto L_0x0213;
        r3 = r3.a();
        r4 = (defpackage.wbz) r4;
        r8 = r4.a;
        r4 = defpackage.abbd.SEARCH_UNSPECIFIED;
        r3.a(r8, r4);
        r5.set(r7);
        goto L_0x003d;
        r6 = r4 instanceof defpackage.wcb;
        if (r6 == 0) goto L_0x003d;
        r6 = r3.a();
        r4 = (defpackage.wcb) r4;
        r4 = r4.a;
        r3 = r3.a;
        r7 = defpackage.abbd.SEARCH_UNSPECIFIED;
        r3 = r6.a(r4, r3, r7);
        r4 = new wdd$b;
        r4.<init>(r5);
        r4 = (defpackage.ajev) r4;
        r3 = r3.g(r4);
        r4 = "chatLauncher.launchUnfix… guardClicks.set(false) }";
        goto L_0x0274;
        r0 = r38;
        r3 = r1 instanceof defpackage.wbs;
        r4 = "friendActionProcessor.pr…iend\")\n                })";
        if (r3 == 0) goto L_0x027c;
        r3 = r0.g;
        r5 = r1;
        r5 = (defpackage.wbs) r5;
        r6 = r0.c;
        defpackage.akcr.b(r5, r2);
        defpackage.akcr.b(r6, r7);
        r2 = new ajei;
        r2.<init>();
        r6 = r3.a;
        r6 = r6.b();
        r6 = (defpackage.iqv) r6;
        r7 = r5.e;
        r6 = r6.a(r7);
        r7 = new wcy$c;
        r7.<init>(r3, r5);
        r7 = (defpackage.ajev) r7;
        r3 = r6.b(r7);
        r5 = defpackage.wcy.d.a;
        r5 = (defpackage.ajev) r5;
        r6 = defpackage.wcy.e.a;
        r6 = (defpackage.ajfb) r6;
        r3 = r3.a(r5, r6);
        defpackage.akcr.a(r3, r4);
        defpackage.ajvv.a(r3, r2);
        goto L_0x003d;
        r3 = r1 instanceof defpackage.wcs;
        if (r3 == 0) goto L_0x02f9;
        r3 = r0.h;
        r4 = r1;
        r4 = (defpackage.wcs) r4;
        r5 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r5, r7);
        r2 = r4.d;
        r5 = r2 instanceof defpackage.wbw;
        if (r5 == 0) goto L_0x02ab;
        r2 = new pri;
        r5 = r4.d;
        r5 = (defpackage.wbw) r5;
        r5 = r5.a;
        r4 = r4.d;
        r4 = (defpackage.wbw) r4;
        r4 = r4.b;
        r6 = defpackage.gcn.SEARCH_CONTACT;
        r2.<init>(r5, r4, r6);
        r4 = r2;
        r4 = (defpackage.psg) r4;
        r6 = r4;
        goto L_0x02ca;
        r2 = r2 instanceof defpackage.wcw;
        if (r2 == 0) goto L_0x02c9;
        r2 = new psv;
        r5 = r4.d;
        r5 = (defpackage.wcw) r5;
        r5 = r5.a;
        r6 = r4.d;
        r6 = (defpackage.wcw) r6;
        r6 = r6.b;
        r4 = r4.d;
        r4 = (defpackage.wcw) r4;
        r4 = r4.c;
        r7 = defpackage.gcn.SEARCH_CONTACT;
        r2.<init>(r5, r6, r4, r7);
        goto L_0x02a6;
        r6 = 0;
        if (r6 == 0) goto L_0x02e5;
        r2 = r3.b;
        r3 = new psh;
        r7 = 0;
        r8 = 0;
        r9 = 0;
        r10 = 0;
        r11 = 28;
        r5 = r3;
        r5.<init>(r6, r7, r8, r9, r10, r11);
        r2.a(r3);
        r2 = defpackage.ajfu.b;
        r2 = defpackage.ajek.a(r2);
        goto L_0x0796;
        r2 = r3.a;
        r2 = r2.b();
        r2 = (defpackage.dnv) r2;
        r2 = r2.a();
        r2 = r2.e();
        r3 = "stackedCameraLauncher.la…ackedCamera().subscribe()";
        goto L_0x0384;
        r3 = r1 instanceof defpackage.wcd;
        r5 = "Disposables.empty()";
        if (r3 == 0) goto L_0x0333;
        r3 = r0.i;
        r4 = r1;
        r4 = (defpackage.wcd) r4;
        r6 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r6, r7);
        r2 = r3.a;
        r2 = r2.b();
        r2 = (defpackage.usd) r2;
        r3 = new usq;
        r7 = defpackage.usg.FRIEND_PROFILE;
        r8 = r4.d;
        r9 = r4.e;
        r10 = defpackage.abbd.SEARCH_UNSPECIFIED;
        r11 = 0;
        r12 = 16;
        r6 = r3;
        r6.<init>(r7, r8, r9, r10, r11, r12);
        r2.a(r3);
        r2 = defpackage.ajfu.b;
        r2 = defpackage.ajek.a(r2);
        defpackage.akcr.a(r2, r5);
        goto L_0x0796;
        r3 = r1 instanceof defpackage.wce;
        if (r3 == 0) goto L_0x0361;
        r3 = r0.j;
        r4 = r1;
        r4 = (defpackage.wce) r4;
        r6 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r6, r7);
        r2 = r3.a;
        r2 = r2.b();
        r2 = (defpackage.usd) r2;
        r3 = new usq;
        r7 = defpackage.usg.GROUP_PROFILE;
        r8 = r4.d;
        r8 = java.lang.String.valueOf(r8);
        r9 = 0;
        r10 = defpackage.abbd.SEARCH_UNSPECIFIED;
        r11 = 0;
        r12 = 20;
        r6 = r3;
        r6.<init>(r7, r8, r9, r10, r11, r12);
        goto L_0x0325;
        r3 = r1 instanceof defpackage.wcg;
        if (r3 == 0) goto L_0x0389;
        r3 = r0.l;
        r4 = r1;
        r4 = (defpackage.wcg) r4;
        r5 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r5, r7);
        r2 = r3.a;
        r3 = r4.d;
        r4 = defpackage.aaua.SEARCH;
        r5 = defpackage.aats.DEFAULT;
        r2 = r2.b(r3, r4, r5);
        r2 = r2.e();
        r3 = "publisherProfileLauncher…Type.DEFAULT).subscribe()";
        defpackage.akcr.a(r2, r3);
        goto L_0x0796;
        r3 = r1 instanceof defpackage.wcc;
        if (r3 == 0) goto L_0x0445;
        r3 = r0.k;
        r4 = r1;
        r4 = (defpackage.wcc) r4;
        r5 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r5, r7);
        r2 = new hvt;
        r5 = r3.d;
        r4 = r4.d;
        r6 = r3.f;
        r7 = r4.d;
        r7 = java.lang.String.valueOf(r7);
        r6 = r6.a(r7);
        if (r6 == 0) goto L_0x03b5;
        r6 = r6.booleanValue();
        r16 = r6;
        goto L_0x03b7;
        r16 = 0;
        r6 = r3.g;
        r7 = r4.d;
        r7 = java.lang.String.valueOf(r7);
        r6 = r6.a(r7);
        if (r6 == 0) goto L_0x03cc;
        r6 = r6.booleanValue();
        r17 = r6;
        goto L_0x03ce;
        r17 = 0;
        r6 = new hwd;
        r8 = r4.a;
        r9 = r4.b;
        r10 = r4.c;
        r11 = r4.d;
        r13 = r4.e;
        r15 = r4.f;
        r7 = r6;
        r7.<init>(r8, r9, r10, r11, r13, r15, r16, r17);
        r4 = r3.l;
        r7 = r3.m;
        r8 = r3.h;
        r9 = r3.e;
        r10 = r3.i;
        r11 = r3.f;
        r12 = r3.g;
        r13 = r3.j;
        r14 = r3.k;
        r15 = r3.n;
        r31 = 249888; // 0x3d020 float:3.50168E-40 double:1.23461E-318;
        r18 = r2;
        r19 = r5;
        r20 = r6;
        r21 = r4;
        r22 = r7;
        r23 = r8;
        r24 = r11;
        r25 = r12;
        r26 = r10;
        r27 = r9;
        r28 = r13;
        r29 = r14;
        r30 = r15;
        r18.<init>(r19, r20, r21, r22, r23, r24, r25, r26, r27, r28, r29, r30, r31);
        r2 = defpackage.ajdx.b(r2);
        r4 = r3.c;
        r4 = r4.h();
        r4 = (defpackage.ajdw) r4;
        r2 = r2.b(r4);
        r4 = r3.c;
        r4 = r4.l();
        r4 = (defpackage.zfr) r4;
        r4 = (defpackage.ajdw) r4;
        r2 = r2.a(r4);
        r4 = new wde$b;
        r4.<init>(r3);
        r4 = (defpackage.ajfb) r4;
        r3 = defpackage.wde.c.a;
        r3 = (defpackage.ajfb) r3;
        r2 = r2.a(r4, r3);
        r3 = "Single.just(\n           …u $t\")\n                })";
        goto L_0x0384;
        r3 = r1 instanceof defpackage.wch;
        if (r3 == 0) goto L_0x0463;
        r3 = r0.m;
        r4 = r1;
        r4 = (defpackage.wch) r4;
        r6 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r6, r7);
        r2 = r3.a;
        r3 = r4.d;
        r4 = defpackage.aaua.SEARCH;
        r6 = defpackage.aats.DEFAULT;
        r2.b(r3, r4, r6);
        goto L_0x0328;
        r3 = r1 instanceof defpackage.wck;
        if (r3 == 0) goto L_0x04ea;
        r3 = r0.n;
        r4 = r1;
        r4 = (defpackage.wck) r4;
        r5 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r5, r7);
        r2 = new ajei;
        r2.<init>();
        r11 = r4.d;
        r7 = r4.e;
        r9 = r4.f;
        r6 = r4.h;
        r12 = r3.a();
        r31 = r12.b();
        r12 = r3.a();
        r33 = r12.c();
        r12 = 1;
        r13 = 0;
        r12 = r5.compareAndSet(r13, r12);
        if (r12 != 0) goto L_0x049b;
        goto L_0x003d;
        r12 = new wdk$c;
        r26 = r12;
        r27 = r3;
        r28 = r6;
        r29 = r11;
        r30 = r4;
        r35 = r2;
        r26.<init>(r27, r28, r29, r30, r31, r33, r35);
        r13 = new wdk$d;
        r13.<init>(r3, r4);
        r4 = r3.b;
        r4 = r4.b();
        r6 = r4;
        r6 = (defpackage.war) r6;
        r4 = r6.a(r7, r9, r11);
        r6 = r3.a;
        r6 = r6.l();
        r6 = (defpackage.zfr) r6;
        r6 = (defpackage.ajdw) r6;
        r4 = r4.a(r6);
        r6 = new wdk$e;
        r6.<init>(r3, r12, r5);
        r6 = (defpackage.ajfc) r6;
        r4 = r4.e(r6);
        r6 = defpackage.wdk.f.a;
        r6 = (defpackage.ajev) r6;
        r7 = new wdk$g;
        r7.<init>(r3, r5, r13);
        r7 = (defpackage.ajfb) r7;
        r3 = r4.a(r6, r7);
        r4 = "publisherStoryLookupAndP…Menu()\n                })";
        goto L_0x0274;
        r3 = r1 instanceof defpackage.wbx;
        if (r3 == 0) goto L_0x050a;
        r3 = r0.q;
        r4 = r1;
        r4 = (defpackage.wbx) r4;
        r6 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r6, r7);
        r2 = r3.a;
        r3 = 2131889367; // 0x7f120cd7 float:1.9413396E38 double:1.053293297E-314;
        r4 = 0;
        r2 = android.widget.Toast.makeText(r2, r3, r4);
        r2.show();
        goto L_0x0328;
        r3 = r1 instanceof defpackage.wcr;
        if (r3 == 0) goto L_0x0541;
        r3 = r0.p;
        r5 = r1;
        r5 = (defpackage.wcr) r5;
        r6 = r0.c;
        defpackage.akcr.b(r5, r2);
        defpackage.akcr.b(r6, r7);
        r2 = new ajei;
        r2.<init>();
        r6 = r3.a;
        r6 = r6.b();
        r6 = (defpackage.iqv) r6;
        r7 = r5.e;
        r6 = r6.a(r7);
        r7 = new wdm$c;
        r7.<init>(r3, r5);
        r7 = (defpackage.ajev) r7;
        r3 = r6.b(r7);
        r5 = defpackage.wdm.d.a;
        r5 = (defpackage.ajev) r5;
        r6 = defpackage.wdm.e.a;
        goto L_0x026e;
        r3 = r1 instanceof defpackage.wcj;
        if (r3 == 0) goto L_0x05ed;
        r3 = r0.o;
        r4 = r1;
        r4 = (defpackage.wcj) r4;
        r5 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r5, r7);
        r2 = new ajei;
        r2.<init>();
        r6 = r4.d;
        r7 = r4.e;
        r8 = r4.g;
        r9 = r4.h;
        r10 = r3.a();
        r32 = r10.b();
        r10 = r3.a();
        r34 = r10.c();
        r10 = 1;
        r11 = 0;
        r10 = r5.compareAndSet(r11, r10);
        if (r10 != 0) goto L_0x0579;
        goto L_0x003d;
        r10 = new wdj$c;
        r26 = r10;
        r27 = r3;
        r28 = r6;
        r29 = r8;
        r30 = r9;
        r31 = r7;
        r36 = r4;
        r37 = r2;
        r26.<init>(r27, r28, r29, r30, r31, r32, r34, r36, r37);
        r4 = r3.b;
        r4 = r4.b();
        r4 = (defpackage.waq) r4;
        r7 = "dynamicStoryId";
        defpackage.akcr.b(r6, r7);
        r7 = r4.b;
        r8 = com.snap.core.db.column.FeatureType.SEARCH;
        r7 = r7.a(r6, r8);
        r8 = r4.a;
        r8 = r8.l();
        r8 = (defpackage.zfr) r8;
        r8 = (defpackage.ajdw) r8;
        r7 = r7.a(r8);
        r8 = new waq$a;
        r8.<init>(r4, r6);
        r8 = (defpackage.ajfc) r8;
        r4 = r7.a(r8);
        r6 = "dynamicStorySnapMediaRep…      }\n                }";
        defpackage.akcr.a(r4, r6);
        r6 = r3.a;
        r6 = r6.l();
        r6 = (defpackage.zfr) r6;
        r6 = (defpackage.ajdw) r6;
        r4 = r4.a(r6);
        r6 = new wdj$d;
        r6.<init>(r3, r10, r5);
        r6 = (defpackage.ajfc) r6;
        r4 = r4.e(r6);
        r6 = defpackage.wdj.e.a;
        r6 = (defpackage.ajev) r6;
        r7 = new wdj$f;
        r7.<init>(r3, r5);
        r7 = (defpackage.ajfb) r7;
        r3 = r4.a(r6, r7);
        r4 = "dynamicStoryLookupAndPer…CONDS)\n                })";
        goto L_0x0274;
        r3 = r1 instanceof defpackage.wci;
        if (r3 == 0) goto L_0x061f;
        r3 = r0.r;
        r4 = r1;
        r4 = (defpackage.wci) r4;
        r5 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r5, r7);
        r2 = r4.a;
        r2 = r2.a();
        r2 = r2.k();
        r4 = "event.profile.businessProfile.toProto()";
        defpackage.akcr.a(r2, r4);
        r3 = r3.a;
        r4 = defpackage.aaua.SEARCH;
        r5 = defpackage.aats.DEFAULT;
        r2 = r3.a(r2, r4, r5);
        r2 = r2.e();
        r3 = "publicProfileLauncher.la…Type.DEFAULT).subscribe()";
        goto L_0x0384;
        r3 = r1 instanceof defpackage.wcu;
        if (r3 == 0) goto L_0x0663;
        r3 = r0.s;
        r4 = r1;
        r4 = (defpackage.wcu) r4;
        r5 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r5, r7);
        r2 = new yup;
        r5 = r4.a;
        r6 = new yuv;
        r7 = r4.b;
        r8 = r4.c;
        r9 = r4.d;
        r10 = 0;
        r6.<init>(r7, r8, r9, r10);
        r7 = r4.d;
        r2.<init>(r5, r6, r7);
        r3 = r3.a;
        r2 = (defpackage.yus) r2;
        r2 = r3.a(r2);
        r3 = new wdq$b;
        r3.<init>(r4);
        r3 = (defpackage.ajfb) r3;
        r5 = new wdq$c;
        r5.<init>(r4);
        r5 = (defpackage.ajfb) r5;
        r2 = r2.a(r3, r5);
        r3 = "subscriptionDataSource\n …vent\")\n                })";
        goto L_0x0384;
        r3 = r1 instanceof defpackage.wcl;
        if (r3 == 0) goto L_0x06b7;
        r3 = r0.t;
        r4 = r1;
        r4 = (defpackage.wcl) r4;
        r6 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r6, r7);
        r2 = 1;
        r7 = 0;
        r2 = r6.compareAndSet(r7, r2);
        if (r2 != 0) goto L_0x067e;
        goto L_0x0328;
        r2 = r4.f;
        r2.setVisibility(r7);
        r2 = new ajei;
        r2.<init>();
        r5 = r3.b;
        r5 = r5.b();
        r5 = (defpackage.kgq) r5;
        r8 = r4.a;
        r5 = r5.b(r8, r7);
        r7 = new wdp$b;
        r7.<init>(r3, r4, r2, r6);
        r7 = (defpackage.ajfc) r7;
        r3 = r5.e(r7);
        r5 = new wdp$c;
        r5.<init>(r4);
        r5 = (defpackage.ajev) r5;
        r7 = new wdp$d;
        r7.<init>(r4, r6);
        r7 = (defpackage.ajfb) r7;
        r3 = r3.a(r5, r7);
        r4 = "snapProClient\n          …tory\")\n                })";
        goto L_0x0274;
        r3 = r1 instanceof defpackage.wct;
        if (r3 == 0) goto L_0x073a;
        r3 = r0.u;
        r4 = r1;
        r4 = (defpackage.wct) r4;
        r6 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r6, r7);
        r2 = 1;
        r7 = 0;
        r2 = r6.compareAndSet(r7, r2);
        if (r2 != 0) goto L_0x06d1;
        goto L_0x067c;
        r2 = r3.c;
        r2 = r2.e();
        r5 = new wdr$b;
        r5.<init>(r3, r4);
        r5 = (defpackage.ajfc) r5;
        r2 = r2.a(r5);
        r4 = "commerceControls\n       …bled(event, enabledDev) }";
        defpackage.akcr.a(r2, r4);
        r4 = r3.a;
        r4 = r4.f();
        r4 = (defpackage.ajdw) r4;
        r2 = r2.b(r4);
        r4 = new wdr$c;
        r4.<init>(r3);
        r4 = (defpackage.ajfc) r4;
        r2 = r2.f(r4);
        r4 = new wdr$d;
        r4.<init>(r3);
        r4 = (defpackage.ajfc) r4;
        r2 = r2.e(r4);
        r3 = r3.a;
        r3 = r3.l();
        r3 = (defpackage.zfr) r3;
        r3 = (defpackage.ajdw) r3;
        r2 = r2.b(r3);
        r3 = 1;
        r5 = java.util.concurrent.TimeUnit.SECONDS;
        r2 = r2.b(r3, r5);
        r3 = new wdr$e;
        r3.<init>(r6);
        r3 = (defpackage.ajev) r3;
        r2 = r2.f(r3);
        r3 = defpackage.wdr.f.a;
        r3 = (defpackage.ajev) r3;
        r4 = defpackage.wdr.g.a;
        r4 = (defpackage.ajfb) r4;
        r2 = r2.a(r3, r4);
        r3 = "getStoreUri(event)\n     …owable, \"Launch error\")})";
        goto L_0x0384;
        r3 = r1 instanceof defpackage.wcf;
        if (r3 == 0) goto L_0x075b;
        r2 = r0.v;
        r3 = r1;
        r3 = (defpackage.wcf) r3;
        r4 = r0.c;
        r5 = "action";
        defpackage.akcr.b(r3, r5);
        defpackage.akcr.b(r4, r7);
        r2 = r2.a;
        r2 = r2.a();
        r2 = r2.e();
        r3 = "openMapActionProcessor.p…penMapEvent().subscribe()";
        goto L_0x0384;
        r3 = r1 instanceof defpackage.wbu;
        if (r3 == 0) goto L_0x07b5;
        r3 = r0.w;
        r4 = r1;
        r4 = (defpackage.wbu) r4;
        r6 = r0.c;
        defpackage.akcr.b(r4, r2);
        defpackage.akcr.b(r6, r7);
        r2 = 1;
        r7 = 0;
        r2 = r6.compareAndSet(r7, r2);
        if (r2 != 0) goto L_0x0776;
        goto L_0x067c;
        r2 = r4.a;
        r4 = new wda$b;
        r4.<init>(r3, r2);
        r4 = (java.util.concurrent.Callable) r4;
        r2 = defpackage.ajdx.c(r4);
        r3 = new wda$c;
        r3.<init>(r6);
        r3 = (defpackage.ajev) r3;
        r2 = r2.b(r3);
        r2 = r2.c();
        r3 = "Single.fromCallable {\n  ….set(false) }.subscribe()";
        goto L_0x0384;
        r3 = r0.b;
        r3.a(r2);
        r2 = r1 instanceof defpackage.wbr;
        if (r2 == 0) goto L_0x07b4;
        r2 = r0.a;
        r2 = r2.b();
        r2 = (defpackage.vzn) r2;
        r1 = (defpackage.wbr) r1;
        r3 = r1.c;
        r4 = r1.b;
        r5 = defpackage.aayg.SEARCH_RESULTS_PAGE;
        r1 = r1.a;
        r2.a(r3, r4, r5, r1);
        return;
        r1 = new ajxk;
        r1.<init>();
        throw r1;
        return;
        */
        throw new UnsupportedOperationException("Method not decompiled: defpackage.way.onSearchAction(wbq):void");
    }

    @akqq(a = ThreadMode.MAIN)
    public final void onSearchDismissAction(wbt wbt) {
        akcr.b(wbt, "event");
        dispose();
        Context context = this.d;
        if (context != null) {
            ((Activity) context).onBackPressed();
            return;
        }
        throw new ajxt("null cannot be cast to non-null type android.app.Activity");
    }
}
