package com.snap.core.db.record;

import com.snap.core.db.record.MessageModel.GetSnapInfoWithContentFromMessageByMessageIdModel;
import com.snap.core.db.record.MessageModel.GetSnapOperaInfoByRowIdModel;
import com.snap.core.db.record.MessageModel.GetSnapsFromMessageForFeedModel;
import com.snap.core.db.record.MessageModel.GetSnapsOlderThanTimestampModel;
import com.snap.core.db.record.MessageRecord.BasicInfoForMessageModel;
import com.snap.core.db.record.MessageRecord.GetContentForMessageModel;
import com.snap.core.db.record.MessageRecord.GetSnapInfoFromMessageWithMessageIdModel;
import com.snap.core.db.record.MessageRecord.GetSnapStatesByMessageIds;
import com.snap.core.db.record.MessageRecord.LastMessage;
import com.snap.core.db.record.MessageRecord.LastMessageWithClientStatus;
import com.snap.core.db.record.MessageRecord.LastReceivedNotViewedChat;
import com.snap.core.db.record.MessageRecord.LastReceivedNotViewedUpdateMessage;
import com.snap.core.db.record.MessageRecord.LastReceivedViewedChat;
import com.snap.core.db.record.MessageRecord.LastReleasedChat;
import com.snap.core.db.record.MessageRecord.LastSentNotViewedChat;
import com.snap.core.db.record.MessageRecord.LastSentSnapModel;
import com.snap.core.db.record.MessageRecord.LastSentViewedChat;
import com.snap.core.db.record.MessageRecord.LastViewedMessageModel;
import com.snap.core.db.record.MessageRecord.MessageDifferentialInfo;
import com.snap.core.db.record.MessageRecord.MessageDump;
import com.snap.core.db.record.MessageRecord.MessageInfo;
import com.snap.core.db.record.MessageRecord.MessageMediaForIdInfo;
import com.snap.core.db.record.MessageRecord.MessageMediaForKeyInfo;
import com.snap.core.db.record.MessageRecord.MischiefPlayableSnapInfo;
import com.snap.core.db.record.MessageRecord.PlayableSnap;
import com.snap.core.db.record.MessageRecord.ReceivedSnapsModel;
import com.snap.core.db.record.MessageRecord.SnapDifferentialInfo;
import com.snap.core.db.record.MessageRecord.SnapMetadata;
import com.snap.core.db.record.MessageRecord.SnapUpdateInfo;
import com.snap.core.db.record.MessageRecord.SnapUpdateInfoNew;
import com.snap.core.db.record.MessageRecord.WithFriend;
import defpackage.ainw;

public class LegacyMessageQueries {
    public static final ainw<BasicInfoForMessageModel> BASIC_INFO_FOR_MESSAGE_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getBasicInfoForMessageMapper(-$$Lambda$_Po_wyOeP8o3GwVk_xzKYMgTV10.INSTANCE);
    public static final ainw<GetContentForMessageModel> GET_CONTENT_FOR_MESSAGE_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getContentForMessagesMapper(-$$Lambda$wl3FP7GJRwlzZM4wv84_QWautw0.INSTANCE);
    public static final ainw<GetSnapsFromMessageForFeedModel> GET_SNAPS_FOR_FEED_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getSnapsFromMessageForFeedMapper(-$$Lambda$3VLMjETwX7Z2DR1XFm7c9cPj5w4.INSTANCE);
    public static final ainw<GetSnapsOlderThanTimestampModel> GET_SNAPS_OLDER_THAN_TIMESTAMP_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getSnapsOlderThanTimestampMapper(-$$Lambda$Dy65SnQAZd9Lfk1Ja1Uwc-Pz2V0.INSTANCE);
    public static final ainw<GetSnapInfoFromMessageWithMessageIdModel> GET_SNAP_INFO_FROM_MESSAGE_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getSnapInfoFromMessageByMessageIdMapper(-$$Lambda$wNnJEFCBrL2Z6r7igc3fqLjFgHM.INSTANCE);
    public static final ainw<GetSnapInfoWithContentFromMessageByMessageIdModel> GET_SNAP_INFO_WITH_CONTENT_FROM_MESSAGE_BY_MESSAGE_ID_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getSnapInfoWithContentFromMessageByMessageIdMapper(-$$Lambda$g54RJbLyF7YOki-SDaFYTni9mqs.INSTANCE);
    public static final ainw<GetSnapOperaInfoByRowIdModel> GET_SNAP_OPERA_INFO_BY_ROW_ID_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getSnapOperaInfoByRowIdMapper(-$$Lambda$XgLx2MsIwSU41rpmJWDPVyzQN4U.INSTANCE, FeedRecord.FACTORY);
    public static final ainw<GetSnapStatesByMessageIds> GET_SNAP_STATES_BY_MESSAGE_IDS_ROW_MAPPER = MessageRecord.FACTORY.getSnapStatesByIdsMapper(-$$Lambda$rvEwGL02_sWfz_kNN2HXk4xU7Qo.INSTANCE);
    public static final ainw<LastMessageWithClientStatus> LAST_MESSAGE_WITH_CLIENT_STATUS_ROW_MAPPER = MessageRecord.FACTORY.getLastMessageForMessageClientStatusMapper(-$$Lambda$PC3UlOEn_28x4h2TM4Dh3wrgEqY.INSTANCE);
    public static final ainw<LastReceivedNotViewedChat> LAST_RECEIVED_NOT_VIEWED_CHAT_ROW_MAPPER = MessageRecord.FACTORY.getLastReceivedNotViewedChatMapper(-$$Lambda$y1BgQ0xkFxvi56hUvWyAyiS-SzA.INSTANCE, FeedRecord.FACTORY);
    public static final ainw<LastReceivedViewedChat> LAST_RECEIVED_VIEWED_CHAT_ROW_MAPPER = MessageRecord.FACTORY.getLastReceivedViewedChatMapper(-$$Lambda$ReBVKG9kKjMBpqygvfcEux6zALE.INSTANCE);
    public static final ainw<LastReleasedChat> LAST_RELEASED_CHAT_ROW_MAPPER = MessageRecord.FACTORY.getLastReleasedChatMapper(-$$Lambda$tYer1UBxhO2Kj1yWw7sOkTnaBnE.INSTANCE);
    public static final ainw<LastSentNotViewedChat> LAST_SENT_NOT_VIEWED_CHAT_ROW_MAPPER = MessageRecord.FACTORY.getLastSentNotViewedChatMapper(-$$Lambda$mQ4_Ou7zaJiEhlpDpjzmdWNV0x8.INSTANCE, FriendRecord.FACTORY);
    public static final ainw<LastSentSnapModel> LAST_SENT_SNAP_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getLastSentSnapForMessageMapper(-$$Lambda$ZiA5bQnlw3KJIPn0AkEwf9nTnzE.INSTANCE, FriendRecord.FACTORY);
    public static final ainw<LastSentViewedChat> LAST_SENT_VIEWED_CHAT_ROW_MAPPER = MessageRecord.FACTORY.getLastSentViewedChatMapper(-$$Lambda$F7nW45zpT7zK732O5lc_s-vcd7s.INSTANCE);
    public static final ainw<LastReceivedNotViewedUpdateMessage> LAST_UPDATE_MESSAGE_ROW_MAPPER = MessageRecord.FACTORY.getLastReceivedNotViewedUpdateMessageMapper(-$$Lambda$TLA-id2LXtabfQFhHV09j6A6-Yo.INSTANCE, FeedRecord.FACTORY);
    public static final ainw<LastViewedMessageModel> LAST_VIEWED_MESSAGE_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getLastViewedMessageMapper(-$$Lambda$fmscX62wZ4R_Z0B5lOGOQcaQLSg.INSTANCE);
    public static final ainw<MessageDump> MESSAGE_DUMP_ROW_MAPPER = MessageRecord.FACTORY.messageDumpMapper(-$$Lambda$gHMO8UXUCqvxvjqXx4G_UyRHK5c.INSTANCE);
    public static final ainw<MessageInfo> MESSAGE_INFO_ROW_MAPPER = MessageRecord.FACTORY.getMessageByKeyMapper(-$$Lambda$iU1i_HbtN4tO_AoLgcd3akJC7iI.INSTANCE);
    public static final ainw<MessageMediaForIdInfo> MESSAGE_MEDIA_INFO_ID_MAPPER = MessageRecord.FACTORY.getMessageMediaInfoForIdMapper(-$$Lambda$_PaB5eeD8T0Q2LvUvpovTK3Y1-k.INSTANCE);
    public static final ainw<MessageMediaForKeyInfo> MESSAGE_MEDIA_INFO_KEY_MAPPER = MessageRecord.FACTORY.getMessageMediaInfoForKeyMapper(-$$Lambda$N1Opv1v9hVPGZP2y6fsLPZHNwc4.INSTANCE, MessagingSnapRecord.FACTORY);
    public static final ainw<MischiefPlayableSnapInfo> MISCHIEF_INFO_MAPPER = MessageRecord.FACTORY.getMessageMediaInfoForSnapIdMapper(-$$Lambda$yxhfWy1AiVa-OZNVtJ0MjwVX8rU.INSTANCE, MessagingSnapRecord.FACTORY, SnapRecord.FACTORY);
    public static final ainw<ReceivedSnapsModel> RECEIVED_SNAPS_MODEL_ROW_MAPPER = MessageRecord.FACTORY.getReceivedSnapsMapper(-$$Lambda$kW2gCw5zp3UmdWSKBZLZEzlLQKY.INSTANCE);
    public static final ainw<WithFriend> SELECT_FEED_MESSAGES_MAPPER = MessageRecord.FACTORY.getMessagesForFeedMapper(-$$Lambda$7MJV9ZU3athWFrG3930U_6_te1M.INSTANCE, MessagingSnapRecord.FACTORY, SnapRecord.FACTORY, FeedRecord.FACTORY);
    public static final ainw<LastMessage> SELECT_LAST_MESSAGE_MAPPER = MessageRecord.FACTORY.getLastMessageForFeedExcludingStatusMapper(-$$Lambda$H5CGYLHJsWf1zUEeVhgs2A4BKKw.INSTANCE, SnapRecord.FACTORY, MessagingSnapRecord.FACTORY);
    public static final ainw<MessageDifferentialInfo> SELECT_MESSAGE_INFO_FOR_DIFF = MessageRecord.FACTORY.getMessageInfoForDifferentialUpdateMapper(-$$Lambda$K8JO7HR_h3nxakr91O0aF3Nd0Do.INSTANCE);
    public static final ainw<PlayableSnap> SELECT_PLAYABLE_SNAP_MESSAGES_MAPPER = MessageRecord.FACTORY.getPlayableSnapsForFeedMapper(-$$Lambda$KvObiMiUCdDXDGIAAY9D2r_3JfI.INSTANCE, FeedRecord.FACTORY);
    public static final ainw<SnapDifferentialInfo> SELECT_SNAP_INFO_FOR_DIFF = MessageRecord.FACTORY.getSnapInfoForDifferentialUpdateMapper(-$$Lambda$zqAVwJw2_aTqKpht_1_lLqvwdks.INSTANCE, SnapRecord.FACTORY, MessagingSnapRecord.FACTORY);
    public static final ainw<SnapMetadata> SNAP_METADATA_ROW_MAPPER = MessageRecord.FACTORY.getSnapMetadataForMessageIdMapper(-$$Lambda$amMO88xewBAEztKuQjbDw4dsVXg.INSTANCE, FeedRecord.FACTORY);
    public static final ainw<SnapUpdateInfo> SNAP_UPDATE_INFO_MAPPER = MessageRecord.FACTORY.getSnapMessageInfoForKeyMapper(-$$Lambda$sr29hp7e3-HvGFlvZr1yvnmUCTs.INSTANCE, MessagingSnapRecord.FACTORY);
    public static final ainw<SnapUpdateInfoNew> SNAP_UPDATE_INFO_MAPPER_NEW = MessageRecord.FACTORY.getSnapMessageInfoForKeyNewMapper(-$$Lambda$IZ9OTF4wL1zme8GklxpldP85taM.INSTANCE);
}
